### ISSUE TITLE
Correct URL to ECIPs website on ./ethereumclassic/ECIPs

### ISSUE THREAD

**Issue by TokenHash** [ethereumclassic/ECIPs#109]
I think the link and text to the ECIPs site on ./ethereumclassic/ECIPs should be:

`The Ethereum Classic Improvement Proposal repository is at https://ecips.ethereumclassic.org/`

Currently it's:

`https://ethereumclassic.org/`

...which takes you the home, but that is not the ECIPs site.

**Comment by soc1c** [comment]
I don't understand the issue

**Comment by bobsummerwill** [comment]
I think this has been addressed.

If not, please could you be clearer what you mean, @TokenHash?   Is this something in the README on this repo?

**Comment by TokenHash** [comment]
Oh....it was fixed long ago, but I forgot to close it. Sorry!
