### ISSUE TITLE
ECIP-1056: Agharta EVM and Protocol Upgrades

### ISSUE THREAD

**Issue by sorpaas** [ethereumclassic/ECIPs#131]

**Comment by TokenHash** [comment]
Hi core dev team,

I was wondering if there are any technical chats between yourselves and if Agharta changes are good.

e.g.:

Via EIP-1702 new account version:

- EIP 145 (Bitwise shifting instructions)
- EIP 1014 (Skinny CREATE2 opcode)
- EIP 1052 (EXTCODEHASH opcode)

Is all generally ok with eip-1702, 145, 1014 and 1052? Or are there disagreements that will be sorted out after Atlantis?

**Comment by soc1c** [comment]
yes, all four EIPs make a lot of sense. We should not get distracted now though and focus on Atlantis. Will organize calls after Atlantis

**Comment by YazzyYaz** [comment]
I highly suggest we name the hardfork Agartha instead of Agharta.

Agharta is a Miles Davis album: https://www.youtube.com/watch?v=crpJgZxqMcg

Agartha is the Hollow Earth kingdom: https://en.wikipedia.org/wiki/Agartha

**Comment by BelfordZ** [comment]
Im not sure its been mentioned, but this would make anyone looking to develop a new EVM would need to implement all previous versions as well.

That being said, we must be prudent to ensure that changes are very well documented, and the implementation of each version can be replicated by following this documentation with relative ease.

We should hold off on including this ECIP until the following are very well defined:

What will be the canonical model for describing the EVM
In what format will changes to this model be proposed
where will the model which specifies each version be located?
Further, it would not be wise to make changes to the EVM until this is sorted out. So to be clear, I don't think we should put a date on this HF until the above is sorted out.

**Comment by soc1c** [comment]
what specifically are you referring to?

**Comment by bobsummerwill** [comment]
@BelfordZ When I asked more about EVM versioning on ETH All Core Devs, it was clear that there were two different "levels" of versioning which we need to model:

1. Straight version numbers, which 1702 can handle.
2. Actual deep semantic versioning, which likely needs KEVM-level analysis.

**Comment by BelfordZ** [comment]
@soc1c I was referring to the implicit use of EIP-1702, which has since been removed. Please dismiss above comment.

**Comment by bobsummerwill** [comment]
Please can an ECIP Editor close this issue?  Agharta is shipped.  Thanks!

**Comment by bobsummerwill** [comment]
Thanks, @soc1c
