### ISSUE TITLE
Hands-On Call: Atlantis Hardfork

### ISSUE THREAD

**Issue by soc1c** [ethereumclassic/ECIPs#133]
ref https://github.com/etclabscore/ECIPs/issues/29

### ETC Core Devs Call - Atlantis Hardfork Hands-On

When: **Thursday, September 12, 2019, 2:00 pm UTC, during the expected hardfork**, 120 minutes max.

latest prediction: `2:50:07 pm UTC  |  Thursday, September 12, 2019`

Where: **Ethereum Classic Discord** `#ecips` channel. Will use/create a voice channel _ad hoc._ Ask for an invite here if you are not on that discord.

This will be an _informal_ call for core developers and everyone else interested to monitor the hardfork and discuss progress, eventually, act if necessary.

**Comment by soc1c** [comment]
Block explorer: 

- https://blockscout.com/etc/mainnet
- https://gastracker.io/

Node upgrade status:

- https://gastracker.io/stats/nodes
- #130 

Fork Monitoring:

- http://atlantis.soc1.cz/ (live soon TM)

**Comment by soc1c** [comment]
Latest prediction: `11:19:14 pm UTC | Thursday, September 12, 2019`

**Comment by soc1c** [comment]
Upgrade rate:

![](https://cdn.discordapp.com/attachments/593821590366715905/619109902987558922/unknown.png)

**Comment by TokenHash** [comment]
If the latest prediction is `11:19:14 pm UTC | Thursday, September 12, 2019`

Does that mean the call is likely on the 12th, or is it still on the 13th as written above?

**Comment by zmitton** [comment]
if we are trying to meet during block `8_772_000` that's Thursday but hard to pinpoint. Still I'm calculating anywhere from 13:00 - 16:00 UTC

**Comment by soc1c** [comment]
We are now close enough to estimate it around noon UTC on Thursday

```
11:54:14 am UTC  |  Thursday, September 12, 2019
```

**Comment by soc1c** [comment]
**Call will start at 2pm UTC today!**
