### ISSUE TITLE
Core Devs Call: ECIP-1056 Agharta Upgrade

### ISSUE THREAD

**Issue by soc1c** [ethereumclassic/ECIPs#135]
Ref #131 [ECIP-1056](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1056.md)

### ETC Core Devs Call - Agharta Finalization

When: **Thursday, October 24, 2019, 1pm UTC**, 60 minutes max.

Where: **Ethereum Classic Discord** https://discord.gg/dwxb6nf `#ecips` channel. Will use/create a voice channel _ad hoc._

### Agenda

- Quick client teams check-in
  - Geth Classic / ChainSafe, ETC Labs Core
  - Multi-Geth / Multi-Geth, ETCLabs Core 
  - Parity Ethereum / Parity Tech
  - Mantis / IOHK
  - Hyperledger Besu / ChainSafe, PegaSys
- Agharta (ECIP-1056) is in _"draft"_ state
  - ECIP-1056 needs to be either **accepted** or _updated_ (or _rejected_)
    - discuss [EIP 145](https://eips.ethereum.org/EIPS/eip-145) (Bitwise shifting instructions)
    - discuss [EIP 1014](https://eips.ethereum.org/EIPS/eip-1014) (Skinny `CREATE2` opcode)
    - discuss [EIP 1052](https://eips.ethereum.org/EIPS/eip-1052) (`EXTCODEHASH` opcode)
    - discuss account versioning ref #86 (EIP-1702)
  - discuss a timeline for the protocol upgrade
    - Morden Classic and Kotti Classic testnet (January?)
    - Ethereum Classic mainnet (March?)
- anything else related to Agharta

### Bonus
- Sha3 / ECIP-1049
- DAG Size / ECIP-1043

Please comment to add items to the agenda

**Comment by TokenHash** [comment]
After checking from the ECIP sponsor @realcodywburns and some others in the ecosystem, I am proposing to add to the agenda a discussion about ECIP-1043: http://ecips.ethereumclassic.org/ECIPs/ecip-1043

I cannot comment on its technical merit or risks (leave that to devs) but the rationale "the DAG has failed at its task and now only serves as a deterrent to broader investment in application specific hardware by competent distributors" if true, is logical and would make mining more open and competitive in ETC among other benefits.

**Comment by TokenHash** [comment]
I propose to add a "post mortem" discussion about the sweeper script running
for State Sweeping bloat for EIP-161.

And to define a process to coordinate with stakeholders for future actions that may destabilize nodes in the network.

**Comment by nishantsharma87** [comment]
+1 to @TokenHash's  post for adding the discussion about ECIP-1043 to the agenda. IMO although this solution may seem like only kicking the can farther down the road, this can resolve the anti-competitive bug that the DAG is for ETC mining until the time more permanent solutions, some of which are under discussion by the community (such as SHA3), are implemented.

**Comment by GregTheGreek** [comment]
Yep will be attending the meeting, speaking on behalf of Gethc and Besu.

**Comment by bobsummerwill** [comment]
I will be on an airplane and unable to attend, but I plan to have submitted an ECIP for an alternative plan to Agharta called "Phoenix" where we have two parallel release lines for each client - one with Constantinople+ETC changes and one with Constantinople+Instanbul+ETC changes.   We would have temp POW + POA networks for each, so 4 testnets in all.

This lets us get to candidate client builds almost immediately, so we attempt to fast follow Instanbul.   We make no decision on whether to do single phase or two phase updates to catch up with ETH.

And all of that can be done in parallel with ECIPS, which will be the critical path.

Please can somebody else be the "champion" of this alternative approach in the meeting?  I have explaining it to Yaz, Anthony, Cody, Afri and Terry, at least, I believe, and think it superior.

**Comment by bobsummerwill** [comment]
Also, whether or not we follow this plan, please let's change the name from Agartha.  I can never spell it corrected.  We need a simpler and more memorable name.

I am advocating for "Phoenix" for obvious reasons.  This will be the HF (whether in a single HF or two-phase) which sees ETC reborn, to advance PAST the ETH protocol.  I cannot think of anything more appropriate to name the HF.

And very simple to remember.  Great for marketing of this HF too.

**Comment by GregTheGreek** [comment]
Can you try and get that in well before the call so everyone has time to read it and understand it. Will make discussion flow much smoother during the call.

> This will be the HF (whether in a single HF or two-phase) which sees ETC reborn, to advance PAST the ETH protocol.

What are we moving past? We're implementing the exact same changes to the best of my knowledge?

**Comment by soc1c** [comment]
We should figure out the clients first before advancing past the Foundation Ethereum protocol.

I believe, having a Phoenix hardfork will just slow us down. Agharta is basically ready to be tested, why not just do it?

**Comment by bobsummerwill** [comment]
@soc1c "Agharta is basically ready to be tested, why not just do it?"
Sure - I guess we can.

@GregTheGreek We will likely also be doing EIP-1702 and EIP-615, and maybe FlyClient, maybe some Swarm bits which may or may not need including in the HF(s).

**Comment by bobsummerwill** [comment]
@soc1c If nothing else, please goodness let's change the name.

**Comment by bobsummerwill** [comment]
@soc1c "Agharta is basically ready to be tested, why not just do it?"

The Phoenix plan would see us having two parallel release plans, one of which would be exactly the same as the current Agharta plan, and one of which would include Instanbul as well.

The worry with the two-phase approach is that it is going to take us several months longer, but without actually giving us any more safety or certainty.   Because the critical path here is going to be human consensus - not the technology.

If we don't have ETC mainnet with Agharta until March, and then have another HF for the Istanbul changes STARTING IN MARCH then we will likely will not complete that for another 6 months, right?   So maybe September 2020?

But the reality is that we could make Constantinople + Instanbul supporting ETC clients for for Parity and MultiGeth today as well.   Yes, it is a slightly moving target and would need to be kept refreshed as ETH keeps moving, but we could do it.

Getting both streams of technical work going now would mean we have long-running testnets for each (POW and POA for each, for 4 testnets in today), and get great certainty - while we work on the human consensus.

I think that we are still likely to ship as two HFs, but I want to start on the second HF now - not wait for months before even starting.

I think we can hit the first HF way before March, and I think we can hit the second HF way before September.

For Parity and MultiGeth, we are mainly just enabling codepaths which already exist.   We don't have the challenges of ETH in having to invent the protocol changes and implement them all intermixed with the human consensus.

Barring for EIP-1702 and EIP-615, which I guess would like hit the second HF.

**Comment by bobsummerwill** [comment]
If my plane has Wifi then I will be there in the meeting tomorrow too.

**Comment by soc1c** [comment]
Potential timeline

- Morden Testnet (_deprecated_), Dec 11, 2019, 12pm UTC, block `5_348_435` (Gethc, Parity)
- Mordor Testnet, Jan 15, 2020, 12pm UTC, block `617_716` (Gethc, Parity, Mgeth)
- Kotti Testnet, Feb 05, 2020, 12pm UTC, block `2_028_202` (Parity, Mgeth)
- Classic Mainnet, Apr 15, 2020, 12pm UTC, _no block number required yet_

**Comment by soc1c** [comment]
Thanks everyone for attending. Notes below:

# ETC Core Devs Call - Agharta Finalization

Date Thursday, October 24, 2019, 1:00pm-1:52 UTC

Attendees:
- bakon
- bobsummerwill
- BTCLovera
- DonaldMcIntyre
- DontPanicBurns
- GregTheGreek
- Kimi Sian-Yu Chen
- OmniEdge
- OrYn
- soc1c
- sorpaas
- stev
- Tj
- tzdybal
- wolf_li
- yaz
- Yebisu

Core devs:
- Attendees include Classic Geth / ChainSafe
- Attendees include Multi Geth / ETCLabs
- Attendees include Parity Ethereum

ECIP-1056 discussions:
- No objections to EIP-145
- No objections to EIP-1014
- No objections to EIP-1052
- Objectsions to EIP-1702
  - need our own Solidity compiler
  - need our own tooling
- Conclusion: Let's prioritize ETH changes first
- Let's keep EIP-1702 in ECIP-1065
- Question: Why not include Istanbul in Agharta?
  - Bob proposes Phoenix 1 and 2
  - Breaking changes in Istanbul
  - Taking too long to implement
  - Classic Geth does not implement it yet
  - Tooling might be screwed
- Chain-parity with ETH main-chain should be the goal
- No one opposes Constantinople EIPs
- ECIP-1702 will be removed from ECIP-1056 in favor of ECIP-1065

- Moving on with timing
  - Afri proposes 6 months timeline
    - Question: why so slow
    - Answer: because ECIP-1702 but that is removed now
    - Afri's proposal rejected
  - New timeline proposed
    - Morden Testnet Nov/13th, 2019
    - Mordor Testnet Nov 20th, 2019
  - Kotti Testnet Dec/11th, 2019
  - **Classic Mainnet Jan/15th, 2020**
- No objections

- Conclusion: Move Agharta to **last call** with decisions made above
  - with EIP 145, 1014, 1052, without 1702
  - with "January-15" timeline

- Side note: ECIP-1050 will also move to _last call_ after this discussion

**Comment by zmitton** [comment]
looks good guys. Sorry I could not attend, but I'm very happy with the above results

**Comment by meowsbits** [comment]
i was late, but there
