### ISSUE TITLE
ECIPs website not showing all ECIP preamble lines

### ISSUE THREAD

**Issue by TokenHash** [ethereumclassic/ECIPs#140]
The ECIPs website does not show all lines of the preambles, so, for example, the discussion link of ECIP-1043 is not showing:

![ecips site lines](https://user-images.githubusercontent.com/29529586/65348298-04999300-db9e-11e9-9977-df009c75128b.png)

I think it's because the php/html/css is calling only up to 5 lines per ECIP, but I think it could be expanded.

I recommend setting the line count to 15 as that is the max amount of lines on a preamble as per ECIP-1000.

Re: http://ecips.ethereumclassic.org/ECIPs/ecip-1043

**Comment by TheEnthusiasticAs** [comment]
I checked your example: The link is showed now. I am assuming after opening a discussion the link will be intergrated.

**Comment by soc1c** [comment]
Fixed in #173
