### ISSUE TITLE
Initial email contact to stakeholders/ notification list for Agharta Hardfork

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/ECIPs#143]
Notification of Agharta plan to make known stakeholders aware of the rough timeline and expected upgrades ahead of the fork:

# 4 contact points:

1. Initial heads up a fork is being discussed, get updated contact info
2. Fork blocks have been decided
3. Fork is 2 weeks out
4. Fork happened and is good to go

# List of contacts:

## Exchanges
- [ ] 55 Global Markets
- [ ] ABCC
- [ ] Abucoins
- [ ] AEX
- [ ] BCEX
- [ ] Bibox
- [ ] BigONE
- [ ] Binance
- [ ] Bit-Z
- [ ] Bitfinex
- [ ] BitForex
- [ ] Bithumb
- [ ] Bitker
- [ ] Bitso
- [ ] BitStar
- [ ] Bittrex
- [ ] BTC Markets
- [ ] BTC Trade UA
- [ ] BTC-Alpha
- [ ] BTCC
- [ ] BTCTrade
- [ ] C2CX
- [ ] Changelly
- [ ] ChaoEX
- [ ] Circle/Poloniex
- [ ] Coinbase/Coinbase Wallet
- [ ] Coinbene
- [ ] Coineal
- [ ] CoinEgg
- [ ] CoinExchange
- [ ] Coinnest
- [ ] Coinone
- [ ] Coinroom
- [ ] Coinsbit
- [ ] Coinsquare
- [ ] CoinTiger
- [ ] Coinut
- [ ] Crex24
- [ ] CryptoCurrencyX
- [ ] CryptoMate
- [ ] Cryptopia
- [ ] DigiFinex
- [ ] DragonEx
- [ ] Evercoin
- [ ] Exmo
- [ ] Exrates
- [ ] Gate.io
- [ ] Gatehub
- [ ] HitBTC
- [ ] Huobi
- [ ] HuobiGlobal
- [ ] IDCM
- [ ] Korbit
- [ ] Kraken
- [ ] Kucoin
- [ ] Lbank
- [ ] LiteBit.eu
- [ ] London Block Exchange
- [ ] Mr. Ripple
- [ ] OKEx
- [ ] Ovis
- [ ] P2PB2B
- [ ] QBTC
- [ ] Qryptos
- [ ] Right BTC
- [ ] Robinhood
- [ ] ShapeShift
- [ ] STEX
- [ ] Tokok
- [ ] Upbit
- [ ] Vebitcoin
- [ ] YoBit
- [ ] ZB com

## Miners/Mining Pools
- [ ] TED LEUNG
- [ ] 0xETH
- [ ] 2miners
- [ ] 91pool
- [ ] AntPool / Bitmain
- [ ] ArsMine
- [ ] BTC-com
- [ ] BW
- [ ] Clona Network
- [ ] CoinFoundry
- [ ] CoinMiners
- [ ] Cominers
- [ ] Comining
- [ ] CruxPool
- [ ] daboehlatresh
- [ ] epool.io
- [ ] Ethermine/Bitfly
- [ ] F2Pool
- [ ] GlobalPool
- [ ] HashOn-Pool
- [ ] MinerTopia
- [ ] MiningPoolHub
- [ ] NanoPool
- [ ] PoolCrypto
- [ ] ProtonMine
- [ ] Rett Anderson
- [ ] SoloMiningPools
- [ ] UUpool
- [ ] ViaBTC
- [ ] Wattpool
- [ ] Coinotron

## Block Explorers
- [ ] BlockScout
- [ ] Etherhub
- [ ] Gastracker
- [ ] Google Query
- [ ] MinerGate
- [ ] Jade Explorer

## Wallets
- [ ] Atomic Wallet
- [ ] Bitpie
- [ ] Cobo
- [ ] Coinomi
- [ ] Emerald Wallet
- [ ] Exodus
- [ ] Guarda
- [ ] JAXX
- [ ] Ledger
- [ ] MyCrypto
- [ ] MyEtherWallet
- [ ] Saturn Wallet
- [ ] Trezor
- [ ] Trust Wallet

## Node Services Providers
- [ ] Ethercluster
- [ ] Ethernode
- [ ] BloqCloud

## Other/PR
- [ ] CoinDesk
- [ ] Bitcoin Magazine
- [ ] Yahoo Finance
- [ ] CoinTelegraph
- [ ] NewsBTC
- [ ] CryptoGlobe
- [ ] CryptoBriefing

**Comment by TheEnthusiasticAs** [comment]
I will contact exchanges, pool miners and wallet operators corresponding to awesome list about agharta call. After fixing the apprx. date of the hf in that call, I will notificate about it too. Thx for the reminding

**Comment by TokenHash** [comment]
I added my most updated list, pls add whoever you see missing, most known large stakeholders are added, all in alphabetical order per category.

@TheEnthusiasticAs we can totally do the coordinated work we did with Atlantis.

**Comment by TheEnthusiasticAs** [comment]
Do you mean, each one contact from his side? Sure @TokenHash

**Comment by realcodywburns** [comment]
Great! Atlantis went well I think. Ideally I think there would be 4 contact points.
1) initial heads up a fork is being discussed, get updated contact info
2) fork blocks have been decided
3) fork is 2 weeks out
4) fork happened and is good to go

**Comment by bobsummerwill** [comment]
I am going to share this with the ETC Global Comms WeChat group.
We should really look for some kind of HackMD or similar scratchpad which we can use everywhere in the world.   Github is inaccessible behind the GWF of China.   Long-term I think the answer to that is to move to a self-hosted Gitlab instance.

But in the meantime for this kind of global coordination task, let's just move this elsewhere.

**Comment by TheEnthusiasticAs** [comment]
It can be left open as a "REMINDER" for future communications

**Comment by TheEnthusiasticAs** [comment]
I will close it as it is done. For Aztlan I already created #256
