### ISSUE TITLE
invoke-signer

### ISSUE THREAD

**Issue by zmitton** [ethereumclassic/ECIPs#147]
Discussion section for `invoke-signer` proposal

Markdown view of spec 👉: https://github.com/ethereumclassic/ECIPs/blob/9791c0b59582a2ed80d915afbf410bc104de20ea/_specs/invoke-signer.md

**Comment by zmitton** [comment]
@bobsummerwill 
> How would this relate to WalletConnect?

bridge-servers = bad

**Comment by bobsummerwill** [comment]
https://walletconnect.org/ for everyone else's benefit.

@zmitton Please can you expand on your bridge servers comment?   Assume I am utterly ignorant of the details of walletconnect and of what you are proposing here and you will not be far from the truth.

**Comment by zmitton** [comment]
Im not an expert on wallet connect. That seems to solve a different problem. It requires servers to bridge devices which would not address the UX issue being solved by the ECIP. wallet connect might be useful for processes requiring automatic signing (like staking), but not for what we are currently seeing as user's behavior.

The issue addressed by the ECIP is dapp signing.

**Comment by zmitton** [comment]
Closed due to this issue:


This approach currently has a flaw that the name of the caller application is not sent to the invoked wallet, so handing control back to the caller app is very difficult. This can be worked around in an app-to-app setting (by passing it as part of the payload), but not in a browser-to-app setting (without complicated "browser sniffing" techniques).
