### ISSUE TITLE
Ratchet Pricing

### ISSUE THREAD

**Issue by zmitton** [ethereumclassic/ECIPs#148]
Discussion section for ratchet-pricing proposal

**Comment by bobsummerwill** [comment]
Please could you link to the proposal, @zmitton?  I do not know what this refers to.

**Comment by zmitton** [comment]
Bob, it's a chicken before the egg problem. How can i put a disscusion-to link before I open this issue? Anyway, here it is finally.

[readable document format](https://github.com/zmitton/ECIPs/blob/rachet-pricing/_specs/ratchet-pricing.md)

I have not made a pull request yet due to conclusions stated, but regardless it seems worth documenting the findings thus far.

**Comment by bobsummerwill** [comment]
Yeah, I know, @zmitton.

I tend to create an issue with nothing in it, then create a pull request pointing back to the issue, and then update the issue.

**Comment by soc1c** [comment]
did you submit the proposal yet @zmitton?

**Comment by bobsummerwill** [comment]
Best to create a pull request for this ECIP, @zmitton.
Get that MD assigned a number and merged into the repo as Draft for further discussion and consideration.

**Comment by q9f** [comment]
Please resubmit a PR
