### ISSUE TITLE
Publish ecips to gh pages

### ISSUE THREAD

**Issue by BelfordZ** [ethereumclassic/ECIPs#164]
the contents of: https://ecips.ethereumclassic.org should be published using GH pages.

**Comment by zmitton** [comment]
I think they are

**Comment by BelfordZ** [comment]
I dont see a GH pages branch... Nor a link to a github pages URL, nor anything that would suggest its scripted to do a GH pages deploy.

TBH I'm thinking of just overhauling this whole repo. It might have been pragmatic, but the current setup is amateur hour. Gonna close this issue and open one another day, outlining a more appropriate structure / process.

**Comment by YazzyYaz** [comment]
@BelfordZ it is GHPages. It uses Jekyll and is published here as a GHPages.

https://github.com/ethereumclassic/ECIPs/blob/master/Gemfile#L11

Not sure why you need to overhaul the current repo? Do you mean development process to contribute to it?

**Comment by BelfordZ** [comment]
No, I mean the fact that this repo's deployment has leaked into its structure. It's very atypical of quality devops. The specs & ecips should be in a format / structure that is independent of the release target. Web is one of potentially many release targets. 

honestly, there is just too many things that are not done to start listing them, hence why I said I would make a proper proposal / PR at a later date.
