### ISSUE TITLE
Core Devs Call: Signaling Process

### ISSUE THREAD

**Issue by sorpaas** [ethereumclassic/ECIPs#195]
* When: To be decided.
* Where: **Ethereum Classic Discord** https://discord.gg/dwxb6nf `#ecips` channel. Will use/create a voice channel _ad hoc._

Discuss several signaling proposals, as this is not resolved since last call. cc @soc1c

**Comment by soc1c** [comment]
Are you suggesting the 20+ people on the last call were incompetent making decisions?

I mean, you are free to have as many calls as you want to. I believe a non-binding signaling process does not need much governance.

**Comment by sorpaas** [comment]
I believe it's your fault as a moderator to frame it improperly. From my listening of the call, there's only a rough consensus on having miner to participate in the signaling process, but there's no consensus on the actual specification for the signaling.

**Comment by soc1c** [comment]
maybe it's your fault not joining the call? diminishing my efforts to move forward is really poor and offensive.

**Comment by sorpaas** [comment]
@soc1c Sure, I did not join the call on time, but I listened to the call afterwards carefully. I believe that you're trying to trick the community by framing the community's decision in an improper way, as said above, and you have not disputed my claim.

**Comment by bobsummerwill** [comment]
Is there any specific proposal or TODO here, @sorpaas?

**Comment by sorpaas** [comment]
@bobsummerwill 1076, 1022 and STATEVOTE (https://specs.that.world/36-statevote/)
