### ISSUE TITLE
Reject ECIP-1063 - Integrated decentralized oracles and smart contracts

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ECIPs#205]
Discussion for https://github.com/ethereumclassic/ECIPs/pull/203

This is just a bad idea, and is never going to happen.
Sorry, Jesse.
But we should reject this and clear out cognitive load.

**Comment by bobsummerwill** [comment]
My suggestion, @meowsbits, would be that we raise this in an ETC Core Developers meeting.
I think there is likely very broad consensus that this makes no sense at the protocol level, and we should Reject this issue to reduce our "working set" and also to avoid giving @26jesse false hope that this might ever happen.

It would actually have been a service to say that to him before he went to all the effort of making this ECIP.

**Comment by TheEnthusiasticAs** [comment]
let's have it in a meeting

**Comment by YazzyYaz** [comment]
Agreed with @TheEnthusiasticAs, this should be discussed in a call.

**Comment by bobsummerwill** [comment]
This was discussed on a call and the Rejection has been merged.
