### ISSUE TITLE
Proposing Meeting Coordinators

### ISSUE THREAD

**Issue by sorpaas** [ethereumclassic/ECIPs#209]
The current core dev meeting coordinator is informally Afri. Afri has said we "can replace me anytime". Given recent actions that Afri were not exactly following the "protocol" and were not exactly "neutral" in his position, I think it would be important to have some coordinator name list ready, in case we want to appoint a new one for all of our meetings.

Please feel free to propose names or propose yourself. Current list:

@YazzyYaz 
@phyro 
@TokenHash 
@developerkevin 
@mikeyb

**Comment by sorpaas** [comment]
I'm proposing @YazzyYaz and @TokenHash. @YazzyYaz has always been an peacemaker during all controversial discussions, and @TokenHash is a long-time member of the Ethereum Classic community who has contributed a lot and has been sticking to the ETC principles.

**Comment by bitcoinheartless** [comment]
I second @YazzyYaz - from experience I find him to be grounded, neutral and as you say a natural peacemaker when it comes to heated discussions in the community. 

@TokenHash would be good for managing logistics and organizing but he's had some major blowups himself and we don't need to add more volatility. @phyro would be my second pick.

**Comment by sorpaas** [comment]
I think @bitcoinheartless has proposed @phyro in addition, and @developerkevin self-proposed to be a coordinator. Thank you!

**Comment by zoulaihui** [comment]
I'm proposing  @TokenHash.

**Comment by bobsummerwill** [comment]
@zoulaihui Donald has already indicated that he cannot commit to ETC volunteering.

**Comment by TheEnthusiasticAs** [comment]
What about @mikeyb, if he has time!? (Beside above mentioned ppl, who I would also suggest)

**Comment by developerkevin** [comment]
Yeah unfortunately Donald already said he can't do any active contributing. We'll see down the line. I'm more than willing to offer my support, though I think "smarter / technical people" or actual devs would be more suited to review individual proposals. 😄 

I have no issue planning and organizing these essential meetings i.e. meeting agenda, coordinate a suitable time with participants and confirm they'll be there, taking notes, watching the clock, keeping the meeting on track etc. 

Whenever you need me, I'll be there. I'll be around. 🎵
