### ISSUE TITLE
Proposing a Picture for the Aztlán Hardfork

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ECIPs#210]
![etc Aztlán hardfork](https://user-images.githubusercontent.com/48069525/69831442-b6ea7800-1229-11ea-8217-7e793754313a.png)

**Comment by bobsummerwill** [comment]
Nice!

**Comment by soc1c** [comment]
I had this, needs some more green though.

![Aztlan-Legendary-Aztec-Land](https://user-images.githubusercontent.com/47772477/69860778-38c4ba80-1297-11ea-86e2-5c66a0c4bbc0.jpg)

**Comment by TheEnthusiasticAs** [comment]
I will put the ETC logo and text to your one later today.

**Comment by TheEnthusiasticAs** [comment]
here you go: 
![etc Aztlán hardfork v2](https://user-images.githubusercontent.com/48069525/69885434-603e7600-12dd-11ea-8f90-ee07be8f7176.png)

**Comment by TheEnthusiasticAs** [comment]
ok, I need some more OKs to close and use it as an Aztlán Hardfork photo

**Comment by soc1c** [comment]
I don't think you can unilaterally decide that Github-OKs are sufficient here. Consensus does not happen on the repository. Can you please schedule a call?

**Comment by bobsummerwill** [comment]
Or before a call, just socialize the options on Discord.

**Comment by TheEnthusiasticAs** [comment]
there is a third one :grin: by one of the responsers to my poll:
https://twitter.com/asis_slm/status/1200847009147695104
![image](https://user-images.githubusercontent.com/48069525/69905033-b7604b80-13ae-11ea-9acf-3d5cd46b0b7c.png)
it is nice too

**Comment by TheEnthusiasticAs** [comment]
another two. 1st version got darker, 3rd got a modification
![etc Aztlán hardfork 1 2](https://user-images.githubusercontent.com/48069525/69913058-5595f500-1433-11ea-8b5e-c7e1c65c8388.png)
![etc Aztlán hardfork v3 1](https://user-images.githubusercontent.com/48069525/69913059-5595f500-1433-11ea-973f-d00c727105ad.png)

**Comment by TheEnthusiasticAs** [comment]
the winner of a wallpaper is the second one with 16 votes:
https://twitter.com/asis_slm/status/1200847215960428550

I am closing this issue
