### ISSUE TITLE
Review of Aztlan hard fork

### ISSUE THREAD

**Issue by sorpaas** [ethereumclassic/ECIPs#226]

**Comment by bobsummerwill** [comment]
Is the purpose of this review the same as #227?
If so, maybe let's close this and move the discussion there?

**Comment by sorpaas** [comment]
@bobsummerwill When opening an issue next time, please first check whether existing similar issues have existed. #226 is definitely older than #227 so the technically correct way would be to close the other issue.

But anyway, since this has nothing to do with ECIP process this time, let me just close #226 to avoid duplication.

**Comment by bobsummerwill** [comment]
Fair enough, except that #227 had a clear description.

#226 had no description to make clear your intent.   You might have been thinking about other kinds of review which made sense.

But thank you!
