### ISSUE TITLE
Aztlan Fork without EIP-1884 leaves an account trie attack vector open

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ECIPs#227]
So how do we handle that?

The ETC Coop has asked ChainSafe for a statement of work analyzing the last 100K blocks in both ETC and ETH to look at frequency of opcodes and actual execution times of those within Hyperledger Besu.

Maybe that is even two separate work items?

Hoped for outcome:

1. Identification of places where client optimization is essential to avoid DOS vectors and actually making those optimizations in Besu (disaster averted)

2. Identification of ways in which the current gasprices are sub-optimal and could be tweaked to be better (EVM optimization - no disaster variant)

And it would also be helpful to do the same systemic "essential optimizations" pass for Parity-Ethereum and Multi-Geth, and I would love that to happen, but the ETC Coop does not have spare money hanging around for that work.

**Comment by sorpaas** [comment]
As said on Twitter, my recommendation would be to call off and skip Aztlan until all issues have been fixed, because based on my last-minute review, ECIP-1061 is certainly rushed, and we'd be better fixing those issues first and/or apply account versioning. I currently cannot think of a way to fix this without account versioning.

However, as the consensus is to move forward with Aztlan, I do not object ECIP-1061 and am certainly fine to just go ahead with the hard fork, because in theory, you can always fix any issues of hard forks with just more hard forks.

**Comment by bobsummerwill** [comment]
I think the rational for moving ahead with Atzlan is that potential attack vectors are currently present and will remain present until we address them.

So if we aren't ready with account versioning then we shouldn't make any gaspricing changes.

But that is no reason NOT to move forward on the other updates which are completely orthogonal.

**Comment by meowsbits** [comment]
@bobsummerwill Can you please describe the attack vector given the current Atlzan specification set before we start working to approach resolution(s)?

**Comment by GregTheGreek** [comment]
@meowsbits Naturally we can't fully disclose the attack. The vector is real, and must be applied to the next HF IMO.

**Comment by sorpaas** [comment]
If we are really *that* worried about the attack -- I want to note that EIP-1884 does not fully fix the attack.

**Comment by meowsbits** [comment]
@GregTheGreek 

> Naturally we can't fully disclose the attack

I hear you on this and understand the motivation. 

But please keep in mind that this is not "__naturally__". This is not a given characteristic of _all_ attacks. This is unique (there many many known attacks with known solutions) and should be noted as being of particular note for being theoretically unresolved. 

For good form and good documentation, a general outline of what is at stake (scale, scope), status of resolution, and intended approaches to achieving acceptable resolutions (which Bob has started) would be useful.

**Comment by soc1c** [comment]
ref #284 #285

**Comment by bobsummerwill** [comment]
@soc1c We should probably keep this issue open (or a replacement) and tag it with a “Next HF” tag.   Still an open issue.   Still high priority.
