### ISSUE TITLE
Fun Suggestion - Phoenix Day

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ECIPs#233]
Just a fun suggestion.

I propose that we should start referring to 25th March 2020 as "Phoenix Day".

This is when Atzlan hits the ETC mainnet and when it becomes trivial to migrate ETH1 smart contracts for ETC.

That is when Ethereum Classic is truly reborn.

I was talking about renaming of Agharta and Aztlan as Ethereum Classic "Phoenix", phase 1 and 2.

That didn't fly, but what about "Phoenix Day"?    We can meme it up the wazoo and generate so much buzz around that branding.

**Comment by TheEnthusiasticAs** [comment]
It would be more a Phoenix Day 2 (:. But I am joining it.

**Comment by soc1c** [comment]
:+1:
