### ISSUE TITLE
Gas-Limit Configuration Call 

### ISSUE THREAD

**Issue by zmitton** [ethereumclassic/ECIPs#252]
## EDIT: Recording of the call
[HERE] 
https://bobsummerwill.files.wordpress.com/2019/12/192712-etc_gas-limit-configuration-call_discord.mp3
---

### When
Friday, December 27, 2019, 13:00 UTC, 30 minutes.

### Where
Ethereum Classic Discord https://discord.gg/dwxb6nf #ecips channel. Will use/create a voice channel ad hoc.

### Meeting Coordinator
Zac Mitton

### Agenda

Discussion to inform /request miners to change their settings/configuration of target `block-gas-limit`.

As predicted, blocks are beginning to fill up at similar rates to Ethereum (1gb per day or more). Most of this traffic is coming from GasToken, a smart contract who's goal is to fill every block up as much as it can. The amount they can fill it, is determined by miners, who "target" this limit in their node's settings.

Goal of this call is to organize outreach to miners and mining pools of the problem, so they can make informed decisions.

**Comment by zmitton** [comment]
[Gas Token Miner](https://forum.saturn.network/t/how-to-use-gastoken-miner/2433/20)

[ECIP 1047(Reduce Gas Limit to 1 Million)](https://github.com/ethereumclassic/ECIPs/blob/6f7ea4c76b6123daf8276a4ead4f817891ea1116/_specs/ecip-1047.md)

multi-geth config
```
--targetgaslimit 1000000
```

parity config
```
--gas-floor-target 1000000 --gas-cap 0
```

**Comment by zmitton** [comment]
### Some Observations

 - Greater than 90% of blocks "full" (7,900,000). 
 - Greater than 90% Mostly GasToken.
 - (Before GasToken) Average gas used ~= 100,000 per block

**Comment by TheEnthusiasticAs** [comment]
The notes by Bob and the audio file to the call from today:
https://bobsummerwill.com/2019/12/27/gas-limit-configuration-call/
https://bobsummerwill.files.wordpress.com/2019/12/192712-etc_gas-limit-configuration-call_discord.mp3

**Comment by zmitton** [comment]
### todo
 - Gather gas usage stats
 - Gather miner revenue stats (block reward vs gas fees)

**Comment by zmitton** [comment]
From @bobsummerwill 
1. Outreach ASAP for voluntary gaslimit reduction (to stop the bleeding)
2. Counter-measures against gaslimit (buying tokens) to try to reverse the damage.
3. Potential protocol changes

And those protocol changes could include:

1. Gas price changes
2. Removing opcodes (remove refund opcode, remove selfdestruct)
3. Hard cap gas and curve (my pending ECIP) to give multi-decade certainty.

ACTIONS ITEMS:
- Blog post on https://ethereumclassic.org/ by @zacmitton explaining the situation and appealing to miners to voluntarily reduce gaslimit.  To 1M?  To 2M?  To 4M?
- Outreach on the above (using existing contacts we have used for prior HFs)
- Volunteers to generate pull-requests against Parity-Ethereum, Geth Classic, MultiGeth and Hyperledger Besu which change the defaults for ETC to the same.
- Volunteers to consider countermeasures to reverse as much of the damage-to-date as we can by buying gastokens (using community fund if this is expensive) and then using them to debloat the chain.
- Volunteers to consider protocol changes for the long-term.

From @hitchcott 
right now [...] you can spam an entire full block for (7M gas * 1000 gasPrice) = 0.000000007 ETC or $0.0000000315 USD (if my math is correct)

**Comment by zmitton** [comment]
very obvious spike when gasToken started being mined and continuing onward. before that gas usage was less than 5% current levels:

![image](https://user-images.githubusercontent.com/6954889/71561719-bd922800-2a3f-11ea-879b-fcade68e9821.png)

**Comment by bobsummerwill** [comment]
@zmitton Where is the graph above from?   Something you generated yourself?
Got newer data up to head?
Same question to @YazzyYaz, who was gathering such data from the archival node he is syncing to back BlockScout.

**Comment by zmitton** [comment]
i think yaz posted it on discord

**Comment by bobsummerwill** [comment]
He did!  Which will be why it looks so familiar :-)

**Comment by YazzyYaz** [comment]
@bobsummerwill I used Google BigQuery for getting those data, and the code for it has been shared by me. Anyone can access Google BigQuery to run queries on ETC as long as they have a Google Cloud account. Its even free to run within Kaggle notebooks.

**Comment by bobsummerwill** [comment]
We held the meeting so I am closing this issue.

The GasToken issues are not fully resolved, but we can create new issues for specific tasks as the need arises.
