### ISSUE TITLE
Initial email contact to stakeholders/ notification list for Phoenix (old Aztlán) Hardfork

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ECIPs#256]
Notification of Aztlán plan to make known stakeholders aware of the rough timeline and expected upgrades ahead of the fork:

## 4 contact points:
Initial heads up a fork is being discussed, get updated contact info
Fork blocks have been decided
Fork is 2 weeks out
Fork happened and is good to go

To avoid the spamming of the stakeholders, the list of them will be provided by editors of it in a DM in the ETC discord. Please ask in #hf-communications channel.

Thank You!

**Comment by gitr0n1n** [comment]
Is this issue still active or can it be closed @TheEnthusiasticAs ?

**Comment by TheEnthusiasticAs** [comment]
it can be closed. Thx @gitr0n1n
