### ISSUE TITLE
Jekyll CI/CD does not seem to be working

### ISSUE THREAD

**Issue by bobsummerwill** [ethereumclassic/ECIPs#287]
We have had several commits since https://github.com/ethereumclassic/ECIPs/pull/279 a week ago, but the web view does not reflect those updates.

Any ideas, @realcodywburns?  Thanks!

**Comment by realcodywburns** [comment]
#281 #282 were the only ones merged since the pipline was updated. Both updates appear in ecips.ethereumclassic.org for me. Which is missing?

**Comment by bobsummerwill** [comment]
D'oh!   I see what is happening now.   I was deluding myself over https://github.com/ethereumclassic/ECIPs/pull/285/files.

I was pushing commits, but only into the PR, so of course those will not show up on the website until that PR gets merged.

Ignore me!
