### ISSUE TITLE
web view broken for (some?) ECIPs - frontmatter

### ISSUE THREAD

**Issue by meowsbits** [ethereumclassic/ECIPs#292]
Seems to be an issue with frontmatter. eg. for ECIP-1082

Should this validation be handled on CI?

---

https://ecips.ethereumclassic.org/ECIPs/ecip-1082 

![2020-02-17-115239_842x959_screenshot](https://user-images.githubusercontent.com/45600330/74672820-489fbc80-516b-11ea-8733-990c220cc20e.png)

**Comment by soc1c** [comment]
> Should this validation be handled on CI?

Yeah, it should be validated in CI! :+1: 

@realcodywburns
