### ISSUE TITLE
ECIP-1082 [Discussion]: Fork identifier (`forkid`) protocol fork list specification

### ISSUE THREAD

**Issue by meowsbits** [ethereumclassic/ECIPs#294]
https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1082.md

**Comment by meowsbits** [comment]
> [[@soc1c]](https://github.com/ethereumclassic/ECIPs/pull/291#pullrequestreview-360328878) Can you expand on how this affects classic client? Do I read correctly that we will have this in the clients upstream anyways? 

__How this effects classic clients:__

The `eth/64` networking protocol (currently actively implemented by multi-geth and go-ethereum) introduces the `forkid` field in peer to peer communication.

The value for `forkid` is derived from what the client considers to be "Forks" for the network it's currently configured to operate. For any given set of Forks, a different value is determined (eg. fork blocks at `[42, 196, 255]`=`forkid:0x95de` vs. `[42, 255]`=`forkid:0xdd14`).

In order for Classic clients to derive equal `forkid` values, they need to use equalivalent (canonical) Fork-sets. If they don't, they can generate different `forkid` values (eg. if Parity thinks `1920000` is a Fork block, but multi-geth doesn't think so), and then will have a hard time connecting with one another (if possible at all).

This specification intends to establish a shared understanding of what constitutes the "Forks set" on ETC, so that when speaking eth/64, the clients can derive the same `forkid` and thus use shared vocabulary.

__... we will have this in the clients upstream anyways?__

`forkid` derivation logic (and associated specification implementations) are also supported by clients also for the Ethereum Foundation networks; so yes, multi-geth gets this _logic_ for free from go-ethereum.

This specification does not modify or extend the `forkid` logic (ie the function). It only asserts the values that should be passed to that function, in order that we can expect consistent results between clients running ETC configurations.

**Comment by bobsummerwill** [comment]
Yes, @soc1c, we will get the logic within Parity-Ethereum and from the Geth upstream for Multi-Geth, but canonical **data** for describing the ETC forks is required and needs to be standardized.

**Comment by bobsummerwill** [comment]
Reminding myself about the logic here.
So even when moved to Fiinal, this will need updating per ETC hard fork, won't it?

And just to confirm - it is only Geth and downstreams currently implementing eth/64?   Let me log a ticket versus Besu asking about this.

**Comment by bobsummerwill** [comment]
See also https://github.com/multi-geth/multi-geth/pull/141

**Comment by meowsbits** [comment]
> The test case difference is due to 1920000. I don't think omitting fork block 1920000 is a good idea. Can you explain why that won't cause issues when it syncs between 1920000 to 2500000?
> > https://github.com/multi-geth/multi-geth/pull/141#pullrequestreview-380505139

The general rationale for ECIP-1082 choosing to omit 1920000 from the set of forks is that for Ethereum Classic, there was indeed no fork. 

The scope of concern for syncing at this height would be for a client (`geth`) to be able to adequately (and efficiently) differentiate between nodes providing ETH data and those providing ETC data, and for the node in question to be able to import it's respective blocks correctly.

- ETC clients will mark ETH block 1920000 as invalid; ETH applies state differences at the DAO fork block that will cause the block to be rejected as invalid by ETC clients, since they won't be configured with this manual state override. This will stop a full sync in it's tracks, cause the node to drop the peer it downloaded the bad block from, and go about it's business. For an efficient fast sync, the case is a little more complex. An ETH client will reject ETC blocks, since they will be vetted against the custom `HeaderValidation` logic. ETC clients, however, will have a harder time differentiating their chain, since state may not yet be downloaded. In the worst case scenario, an ETC geth might fast sync from an ETH node as high as the next fork as you've mentioned, and discover then that they'd been mislead, and need to find another peer with which to negotiate a common ancestor, effectively using trial and error to find a peer that serves the valid chain. This scenario can easily be avoided by adding the relevant hash for 1920000 to a white or black list that would be validated against during the Header Validation, perhaps somewhere like [here](https://github.com/multi-geth/multi-geth/blob/05fb90865e1d4b8bbd4f351311dbe4c10557b2b9/consensus/misc/forks.go#L30).
- Thankfully, the `forkid`s for eth/64 ETH and ETC clients are different as of 1150000, which actually allows the protocol to distinguish the networks earlier than is possible otherwise, so clients implementing this protocol are able to disambiguate networks sooner, avoiding the above issue altogether.
- Finally, it is not difficult to imagine a chain configuration::forkid implementation that continues to use the fork block 1920000 for block processing (as currently with multi-geth), but omits 1920000 as an exception during the fork id function.

**Comment by meowsbits** [comment]
Noting from review at above issue a good point .@sorpaas made: if ETC were to keep 1920000 in the fork set, the forkids would be identical to ETH through ~2500000, which would cause an ambiguity.

**Comment by q9f** [comment]
> Reminding myself about the logic here.
> So even when moved to Fiinal, this will need updating per ETC hard fork, won't it?

Just seeing this now. This is correct and moving 1082 to final is not beneficial for the cause. I would propose moving 1082 to an ECB documenting the forkids with the ongoing status _active_.
