### ISSUE TITLE
Core Devs Call: Phoenix Upgrade from Scratch

### ISSUE THREAD

**Issue by soc1c** [ethereumclassic/ECIPs#298]
ref #297 

ref [ECIP-1061](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1061.md) [ECIP-1078](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1078.md) [ECIP-1086](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1086.md)

### ETC Core Devs Call - Phoenix Upgrade from Scratch

When: **Wednesday, February 26, 2019, 1pm UTC**, 60 minutes max.

Where: **Ethereum Classic Discord** https://discord.gg/dwxb6nf `#ecips` channel. Will use/create a voice channel _ad hoc._

### Agenda

- Quick client teams check-in
  - Parity Tech
  - ETC Core
  - ChainSafe
  - Multi-Geth
- Aztlán needs to be rejected as it's having multiple issues #217 #226 #227
- Phoenix needs to be rejected as it's not of a sufficient patch especially with the context of the broken testnet activations #262
- Testnet patch should be rejected to favor a clean new hardfork meta #293  #297 
- It's still possible to do Phoenix on the same block number if we agree to activate one of the following options (ECIPs pending):
  - Phoenix hardfork same as ETH Istanbul (including EIP-1884)
  - Phoenix hardfork "classic flavor" (ECIP-1080 instead of 1884, EIP-1706 instead of EIP-2200)
- anything else related to Aztlán and Phoenix

_Please comment to add items to the agenda._

**Comment by GregTheGreek** [comment]
Redoing testnets means we:
- Restart them from scratch (IMO less favourable)
- 51% attack them because theres very little hashrate and just apply the changes that way

**Comment by q9f** [comment]
> Redoing testnets means we:
>   * Restart them from scratch (IMO less favourable)
>   * 51% attack them because theres very little hashrate and just apply the changes that way (favourable)

This is both overdoing it. We can just pull the Aztlan config from the testnets and continue mining the Agharta chain till we hit the new Phoenix block. This wouldn't require neither rebooting them nor 51%ing them.

**Comment by q9f** [comment]
Please review before the call:
* [ECIP-1088: Phoenix EVM Upgrade (Vanilla Option)](https://github.com/ethereumclassic/ECIPs/pull/299)
* [ECIP-1089: Phoenix EVM Upgrade (Classic Option)](https://github.com/ethereumclassic/ECIPs/pull/300)

**Comment by stevanlohja** [comment]
https://medium.com/ethereum-classic-labs/advisory-to-reject-ecip-1061-aztlan-and-ecip-1078-phoenixfix-for-ethereum-classic-28df21a206c

**Comment by meowsbits** [comment]
:studio_microphone: :family:  :record_button: meeting recording https://drive.google.com/open?id=1-LmxtE82Y-sHA7egkKuRzUobJ2IFOkDy

**Comment by q9f** [comment]
attendees:
- bobsummerwill
- DontPanicBurns
- ey
- GregTheGreek
- isaac
- Kimi Sian-Yu Chen
- mackcom
- q9f
- Ray Zou
- stev
- zcstarr

key points of the meeting:
- general agreement about rejecting aztlan (1061), phoenix fix (1078), and testnet fix (1086)
- general agreement about moving on with either vanilla phoenix (1088) or classic phoenix (1089)
- rough consensus on rejecting the old ecips in favor of a clean phoenix
- rough consensus on moving 1088 to last call and withdrawing 1089
- the fork will be called simply "phoenix" (protocol parity day)
- testnets will be reverting to the agharta chain until they hit the 1088 block

recording above by @meowsbits

**Comment by stevanlohja** [comment]
https://youtu.be/HzcJL3rVbpU

**Comment by gitr0n1n** [comment]
So I see precedent to change these gas prices in ECIP-1015 back in 2016. So we are being consistent with that.

"EIP-1884: Repricing for trie-size-dependent opcodes"

**Comment by q9f** [comment]
Ethereum Classic Mainnet Phoenix Hardfork Block `10_500_839` (ECIP-1088):
- Sun, May 31, 2020 (@13.0s blocktime)
- **Fri, Jun 05, 2020** (@14.0s blocktime; _current block time: 13.8s_)
- Wed, Jun 10, 2020 (@15.0s blocktime)

Kotti Classic Testnet Phoenix Hardfork Block `2_200_013` (ECIP-1088):
- **Mon, Apr 13, 2020** (@15.0s blocktime; _assuming no validator downtime_)

Mordor Classic Testnet Phoenix Hardfork Block `999_983` (ECIP-1088):
- Mon, Mar 09, 2020 (_already active; 21 days ago_)
