### ISSUE TITLE
New Picture for The Upcoming Phoenix Upgrade as mentioned in #301

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ECIPs#303]
Let me know, what do you think about this ... :
![ETC Phoenix v1](https://user-images.githubusercontent.com/48069525/75383626-fd10af80-58dc-11ea-9324-1fc8554e0e03.png)

**Comment by bobsummerwill** [comment]
I love it, @TheEnthusiasticAs !

**Comment by TheEnthusiasticAs** [comment]
So, 2d should be enough for such proposal. There is no disagreement on it. So, I am seeing it as positive and going to close this issue.

**Comment by TheEnthusiasticAs** [comment]
In case you want also to use this one 
![ETC Phoenix v2](https://user-images.githubusercontent.com/48069525/75549497-1bd38b00-5a30-11ea-9001-d3b30c1fab8f.png)
