### ISSUE TITLE
CHAINID=0 ; ECIP-1090

### ISSUE THREAD

**Issue by MGiuseppi** [ethereumclassic/ECIPs#317]
Use CHAINID=0

**Comment by MGiuseppi** [comment]
Or Pi.    


I would much rather it be Pi, but imagine the hardware is not yet there.

**Comment by MGiuseppi** [comment]
ChainID=0 accomplishes nothing but a marketing feat.
ChainID=π on the other hand, will permanently keep the CHAINID capped only by our technical's speed.  This secures the network - and our identity.

**Comment by MGiuseppi** [comment]
Consciousness is state that exists only in the present.

If we set chainID=π, our chainID will also serve as a unique principle on our blockchain and one that is perpetually verifying its identity.

It would appear to the general user, like a watermark.

 Running this universally recognized hash of π constantly in our ChainID slot will make etc immediately recognizable and universally appealing, not to mention more secure.

**Comment by q9f** [comment]
`0` is not possible, https://github.com/openethereum/openethereum/issues/8345#issuecomment-429956249

**Comment by MGiuseppi** [comment]
Glad to see zero is possible:

I doubt many will doubt the incredible ramifications that can come from using chainID=π to identify a network.

If we change the current chainID=(null) at all, contracts will be broken.

Use chainID=π to approach all lost contracts:


By utilizing an asymptotic approach to the chainID, we at pay homage to our lost immutability and gain the watermark of Pi.

At most, we utilize chainID=π correctly and make this the perpetual definition of our chain – constantly circling the most recent computed understanding of π.

**Comment by MGiuseppi** [comment]
the math to use a non-integer chainID is more difficult and more suited for a new iteration of digital currency.



ETC should adopt chainID=0

**Comment by gitr0n1n** [comment]
This issue does not appear to have material support. Can we close this one?

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n It is better, if it will be closed / stay opened based on the opinions of the devs, e.g. of @q9f,  @YazzyYaz

**Comment by MGiuseppi** [comment]
.....Of all the disheartening responses....

**Comment by YazzyYaz** [comment]
I think we can keep this one open for the time being and request a formal proposal from @MGiuseppi.

If he can't provide an ECIP draft within an agreed-upon time, then we can close this issue. It can always be re-opened later, but there's nothing specific in our ECIP process about what to do with open issue tickets.

@MGiuseppi can we expect an ECIP draft from you on this? We can use link the discussion page of the draft to this page so more people can discuss your idea.

**Comment by MGiuseppi** [comment]
Please catch me up:

As I understood it, the phoenix hard fork would prevent any future
modifications of chainID.

Since that has occurred, is there a reason to have a dissussion revolving
around how to change it?


If there is still a way to implement change in chainID, I will devote some
attention to it.

**Comment by q9f** [comment]
ref #316
