### ISSUE TITLE
Question to ECIP 1017 - Monetary Policy: Evidence for the Hard Cap of ~230mln

### ISSUE THREAD

**Issue by TheEnthusiasticAs** [ethereumclassic/ECIPs#318]
Can someone please introduce an evidence - e.g. calc table - for the calculation of the hard cap of ~231mln as noted here:
![image](https://user-images.githubusercontent.com/48069525/79077177-c4e3f580-7cff-11ea-8060-de3db708a297.png)
https://ecips.ethereumclassic.org/ECIPs/ecip-1017

I am asking, because this information is circulating without an evidence in the internet.

Thank you.

**Comment by q9f** [comment]
It's linked in the ECIP 

https://docs.google.com/spreadsheets/d/1Fs_RNEPSRJxP22PZmwxWjiulVVcu5Ic1GvBXCPCt9to/edit#gid=640070299
