### ISSUE TITLE
Jekyll build failing

### ISSUE THREAD

**Issue by BelfordZ** [ethereumclassic/ECIPs#319]
![image](https://user-images.githubusercontent.com/1787231/79399654-c6e4c900-7f38-11ea-933c-f3cc3a0e980e.png)

**Comment by meowsbits** [comment]
@ `Jekyll Workflow / build` on master at https://github.com/ethereumclassic/ECIPs/commit/a080e13bab2f0a0866789bb117a8adc424a4d653:

```
Bundle complete! 9 Gemfile dependencies, 91 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
##[error]Process completed with exit code 15.
```
https://github.com/ethereumclassic/ECIPs/runs/727069091?check_suite_focus=true#step:3:168
