### ISSUE TITLE
Informal Call "Phoenix Upgrade and Chill"

### ISSUE THREAD

**Issue by q9f** [ethereumclassic/ECIPs#321]
ref #299 [ECIP-1088](https://github.com/ethereumclassic/ECIPs/blob/master/_specs/ecip-1088.md)

### Informal Call "Phoenix Upgrade and Chill"

When: **Monday, June 1st, 2020, 12~1am UTC**, around fork time. _Check the count-down below for accurate last-minute timing!_

* Count-Down: https://etcnodes.org/phoenix
* Fork-Monitor: https://phoenix.fault.dev
* ETC-Status: http://etcstatus.live
 
Where: **Ethereum Classic Discord** https://discord.gg/dwxb6nf

### Agenda
* _None_ ;-)

**Comment by q9f** [comment]
I might do a live-stream of the fork monitoring on twitch.

**Comment by q9f** [comment]
Fork happens around midnight UTC tonight!

**Comment by gitr0n1n** [comment]
This issue can be closed @q9f
