### ISSUE TITLE
Phoenix Hard-Fork Debrief Meeting

### ISSUE THREAD

**Issue by stevanlohja** [ethereumclassic/ECIPs#324]
# Phoenix Hard-Fork Debrief Meeting

The Phoenix hard-fork was successful so let's talk about it! This meeting is to have a reconciliation of the hard-fork. **If you participated in preparing/ and or coordinating Phoenix, then please join!**

### Location, Date, and Time

_The location, date, and time of this meeting is to be determined._

### Agenda:

- What were we trying to accomplish?
- Where did we hit (or miss) our objectives?
- What caused our results?
- What should we start, stop, or continue doing?
- Anything else...

### Disclaimer

The meeting will be recorded and published on YouTube.

**Comment by TheEnthusiasticAs** [comment]
sry, I got asleep

**Comment by developerkevin** [comment]
Has the meeting already passed or is it still TBD? @stevanlohja

**Comment by q9f** [comment]
I think this never happened.
