### ISSUE TITLE
Housekeeping: Review Systemic Permissioned Roles

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ECIPs#325]
Housekeeping Task:
- Review people's systemic roles and clean out inactive/departed project participants by removing their permissions.
- Where oversight is needed or centralization is occurring, address the issues by decentralizing process power by adding participants that segregate process duties e.g. 2 approvals needed from different members of teams/independent parties.

We need to be honest about decentralizing processes to prevent take overs or attacks. Thanks!

**Comment by gitr0n1n** [comment]
An example, it appears Sorpaas is moving on from ETC to pursue other projects. So it is likely a good time to review his permissioned roles and update permission and repo access based on that annoucement. @YazzyYaz

**Comment by YazzyYaz** [comment]
I don't think we should be removing @sorpaas from the contributor list just because he announced he's not working specifically on ETC. He has many contributions and ideas to the space that warrant thinking more about these decisions than just hastily removing someone because they wrote a blog post.

**Comment by developerkevin** [comment]
I agree with Yaz. We don’t wanna push him out permanently maybe he’s just
going through one of his emotional phases.

**Comment by TheEnthusiasticAs** [comment]
I agree with previous speakers.

**Comment by gitr0n1n** [comment]
> An example, it appears Sorpaas is moving on from ETC to pursue other projects. So it is likely a good time to review his permissioned roles and update permission and repo access based on that annoucement. @YazzyYaz @q9f @stevanlohja

Thank you for addressing this ^ topic via https://github.com/ethereumclassic/ECIPs/pull/326

I'll leave this issue open as a deep review of permissions is likely needed by those with write access to prevent centralized social attacks.

**Comment by realcodywburns** [comment]
emotional phase or not.  This is highly unprofessional behaviour and is not in the spirit of community. He is continuing his mis representation of multigeth as a legitimate source of truth for etc. it isnt. He is doong reputational harm and it should be made abundantly clear that his code and actions don't reflect etc. example: https://github.com/openethereum/openethereum/issues/11829

**Comment by sorpaas** [comment]
I want to make it abundantly clear that my code and actions have nothing to do with ETC any more. I have announced deprecation of ETC already back in June. https://that.world/~classic/2020/06/10/deprecate/

In addition to ETC's loss of immutability, that was also a legitimate and necessary response to the continued toxicity from the ETC community, like the toxicity you see at @realcodywburns's comments.

Clients I have involved in, MultiGeth and OpenEthereum, at the time of deprecation consisting of ~70% ETC total node count, have also both announced deprecation of ETC support. https://twitter.com/sorpaas/status/1283953287495135232

I also want to make it abundantly clear that anyone who [tries to claim](https://github.com/ethereumclassic/ECIPs/issues/325#issuecomment-664695474) that any of my action still has anything to do with ETC is either trying to scam you, or doing a misinformation campaign. If that happens, just ask the person for first-hand direct-quote proofs, which he/she won't be able to provide any.

**Comment by gitr0n1n** [comment]
> He is continuing his mis representation of multigeth as a legitimate source of truth for etc. it isnt.

Good point on his efforts to represent his writing as legimate sources of truth for Ethereum Classic. 

> I want to make it abundantly clear that my code and actions have nothing to do with ETC any more. 

Looking into this right now and I am still seeing Sorpaas represent CorePaper as a legitimate source of truth for ETC as noted by his discord vanity:
https://discord.io/ethereumclassic
https://imgur.com/a/B6frFC1


Back story on this: I believe this vanity was created for CorePaper back when Sopaas amped up his misinformation campaign on Phoenix after ETC reached consensus. This was the link he frequently spammed leading up to the hard fork during his FUD/misinformation campaign. March/April/May 2020 in the ETC discord. This was also the time when he tried to discredit the ECIP process and form his own "RFC process".

Example:
"sorpaas03/14/2020
As I said before it's up to you whether you read it. We'll publish reviews in RFC process and Consensus Paper, and post links in Discord and Reddit. We can ping you directly if you don't follow those communication channels."
"sorpaas-don't-ping-only-PM!04/08/2020
I would happy to invite anyone to join there! So far though all of the --oppose-phoenix-fork discussions have only happened in this Discord."
"sorpaas-don't-ping-only-PM!04/12/2020
Okay guys if you want to find me, you know where! Matrix, Gitter, Telegram, Github or Core Paper discord https://discord.io/ethereumclassic"

This was also around the time when he tried to manufacture an "Anti-Phoenix" faction being censored from the ETC discord and spammed the discord citing his own blog posts on CorePaper. Then waged a Twitter misinformation campaign against the mods for censorship in the ETC discord due to them removing his walls of repeative spam. Of course, in hindsight there was no anti-phoneix faction outside of himself.

"sorpaas-don't-ping-only-PM!03/09/2020
Sorry was just looking for evidence of censorship. Think I got what I need. Thank you!
I don't think anything I sent here has issues - everything is ETC related, and it was to answer someone else's questions. In the long run, censorship will really just hurt this Discord -- blockchain protocols do not tolerate or care about lies. Bugs stay as bugs, unless you fix them.
Anyway, if you're looking for thoughtful and censorship-free discussions, see you on the other side!"

This was then followed by Sorpaas utilizing his permissioned roles in development repo's to add "-oppose-phoenix" flags in Multi-Geth and OpenEthereum to support the manufactured "anti-phoenix" faction.

"sorpaas-don't-ping-only-PM!04/15/2020
We have implemented --oppose-phoenix-fork support in OpenEthereum! A guide on choosing whether you want to support the contested Phoenix hard fork:

* If you support Phoenix, use OpenEthereum, MultiGeth, CoreGeth or Besu, with your usual command line flag
* If you do not support Phoenix, run OpenEthereum with --chain classic-oppose-phoenix-fork or run MultiGeth with --classic --oppose-phoenix-fork

To know more about the contention of Phoenix, you can read more about it here! https://consensus.corepaper.org/wiki/Contention_of_Phoenix_(new)"

"sorpaas-don't-ping-only-PM!04/15/2020
As said, OpenEthereum and MultiGeth aims at remaining neutral. We received requests from other people that they want --oppose-phoenix-fork to be supported, so we do it. This is definitely not about whether me oppose the hard fork. As I have repeatedly said I remain neutral.
This is also why many of us agreed that we should flag this Phoenix hard fork as contested. In Ethereum Classic, users have the final say! :smiley:"

Quite the busy misinformation campaign when you look at the paper trail.

**Comment by q9f** [comment]
A discord vanity address costs around $1000 per year. That's a phishy tactic trying to squat that name, misleading users to believe this is an official representation of the Ethereum Classic community.

**Comment by ellaismer** [comment]
I haven't used this pseudonymous account for years, but I just want to jump in and say that I find the attack and toxicity of @realcodywburns, @gitr0n1n and `@longsats` on Twitter against Ethereum community, OpenEthereum team and @sorpaas disgraceful.

@gitr0n1n I don't find anything wrong in the "proofs" you are accusing against @sorpaas. Everyone are entitled their own opinions. What's wrong with @sorpaas opposing Phoenix hard fork? The reason is also something as important as immutability from your link. https://consensus.corepaper.org/wiki/Contention_of_Phoenix_(new)

I can ask @sorpaas whether he's willing to give up the https://discord.io/ethereumclassic domain, but I don't see that a big problem. Do you own the "Ethereum Classic" trademark?

I wrote MultiGeth and later gave it to @sorpaas for maintanence. Ellaism Core fully supports @sorpaas' decision of removing ETC support. For ETC refugees, please consider joining the Ellaism community! Ellaism has fixed total supply, no pre-mine, stays in POW and is in feature parity with Ethereum Classic.

**Comment by sorpaas** [comment]
@q9f 

> A discord vanity address costs around $1000 per year.

I registered discord.io domains in the past and they are free.

**Comment by sorpaas** [comment]
As I'm not engaged in ETC any more I definitely have no problem giving up the name. I want to ensure it's in the hand of a neutral party, but not those toxic and trouble-making members like @q9f @realcodywburns and @gitr0n1n, nor to any Discord communities that encourages toxicity (like the so-called "main" ETC Discord).

If you have a suitable community you want to link it to, please PM me and let me know.

**Comment by realcodywburns** [comment]
I am removing @sorpaas from the repo as it is unclear whether his accounts are compromised. This is clearly not the actions of a professional and only bring discredit to anything these accounts are associated with.

**Comment by drd34d** [comment]
> I am removing @sorpaas from the repo as it is unclear whether his accounts are compromised. This is clearly not the actions of a professional and only bring discredit to anything these accounts are associated with.

Hopefully someone will remove you too because @realcodywburns account is clearly compromised too.

**Comment by realcodywburns** [comment]
I have blocked ellaismer and sorpaas and any other suspected compromised accounts. I do not have the patients or the time to focus on, to use their phrase, "toxic" belligerent former developers that only have malintent.

**Comment by drd34d** [comment]
> I have blocked ellaismer and sorpaas and any other suspected compromised accounts. I do not have the patients or the time to focus on, to use their phrase, "toxic" belligerent former developers that only have malintent.

Your true colors are showing. Congrats Cody

**Comment by drd34d** [comment]
> I have blocked ellaismer and sorpaas and any other suspected compromised accounts. I do not have the patients or the time to focus on, to use their phrase, "toxic" belligerent former developers that only have malintent.

> I am removing @sorpaas from the repo as it is unclear whether his accounts are compromised. This is clearly not the actions of a professional and only bring discredit to anything these accounts are associated with.

DeCeNtRaLiZeD MuCh

**Comment by realcodywburns** [comment]
I will not facilitate a platform that allows malicious actors to bully developers. If you disagree with this, please open a separate issue for any of the actively banned people. List follows and should all be viewed equally:    

![image](https://user-images.githubusercontent.com/13103499/88686707-f6b97600-d0bc-11ea-9cd0-07bf7c3fe902.png)

**Comment by drd34d** [comment]
Too late to save face dear Cody.  Labeling Sorpaas or Ellaismer as "malicious actors" is probably the dumbest thing you wrote in a while, not that you write much nowadays since you mostly hide behind closed doors sucking corporate dick.
Anyway, have fun playing DeCenTrAlIzEd BlOcKChAinZ.

**Comment by realcodywburns** [comment]
This is also unprofessional and I have reported the content. I will ban the drd34d account if this continues. zero tolerance for bullying.

**Comment by cryptoasuka** [comment]
So... @ellaismer was AFK for years abandoning the ellaism project and its domain and now he is back to github for defending sorpass? 😂 😂

**Comment by drd34d** [comment]
> This is also unprofessional and I have reported the content. I will ban the drd34d account if this continues. zero tolerance for bullying.

Uhhh, I'm being reported. You banned Wei for defending himself but you didn't ban me? Waiting from the director's order to ban me? (hi bob!)

Where was your "zero tolerance" for bullying when bob, afri and 2 other kids were trying to ban Wei on the false pretense of doxxing afri, in order to silence his opposition to the issues found with the fork AND the call notes? 

Where's your "zero tolerance" for lies and bullying like this just now:

> A discord vanity address costs around $1000 per year. That's a phishy tactic trying to squat that name, misleading users to believe this is an official representation of the Ethereum Classic community. 

**This github is nothing is only a show off for ETCG holders to justify their premiums,**

https://github.com/ethereumproject is far gone and the 'lemmings' don't care **why**.

**Comment by realcodywburns** [comment]
I am not sure which director you mean, I am independent. I am on the board of the etc coop, but I do not have any reporting requirements. 

Enjoy your soapbox, but please keep it professional. 
I wish you the best in your future projects.

**Comment by hitchcott** [comment]
@sorpaas

May I nominate myself as a neutral party to inherity the discord handle?

**Comment by realcodywburns** [comment]
is this thread still active? 
Moving to close on 10/1/2020 if no objections

**Comment by gitr0n1n** [comment]
> is this thread still active?
> Moving to close on 10/1/2020 if no objections

No objections from me as the author.
