### ISSUE TITLE
ECIP-1096: 51% Attack protection system based on Bitcoin Merged Mining

### ISSUE THREAD

**Issue by martinmedina** [ethereumclassic/ECIPs#343]
This issue is the discussion for the [ECIP](https://github.com/ethereumclassic/ECIPs/pull/344) that proposes a [51% Attack protection system based on Bitcoin Merged Mining](https://github.com/martinmedina/ECIPs/blob/patch-1/_specs/ecip-51-attack-protection-system.md) (draft)

**Comment by SergioDemianLerner** [comment]
The VisibilityProof proposal establishes an objective cryptoeconomic method to establish the existence of a fork. In the draft proposal we left out how the community or the node wants to react to a visible fork. I think this could be another proposal.
One way to react is use PirlGuard to apply penalties to forks with no public visibility (not VisibilityProofs) of a certain time gap, or with visibility proofs with low hashrate.
You can measure visibility in absolute terms or in relative terms. For example, you can establish that a blockchain fork that has 50% of the visibility hashrate of another branch is condireder hidden for PirlGuard. Or you can consider that a blockchain fork that has less than 33% of Bitcoin hashrate or has a visibility gap of 3 hours or more, is considered hidden.

**Comment by TheEnthusiasticAs** [comment]
Recording of the presentation: https://www.crowdcast.io/e/mqongnrs

**Comment by w1g0** [comment]
> In any case, this ECIP should have proposed merge mining with the Ethereum miner base, so when Ethereum migrates to Ethereum 2.0, the miner base could continue seamlessly on ETC.
> 
That's a good idea but what's in it for Ethereum? They won't invest time and effort if they ain't have any incentive to do so...

**Comment by DonaldMcIntyre** [comment]
> That's a good idea but what's in it for Ethereum?

It does not affect Ethereum, It is just a deal with the ETH miners that have to add some software to their mining software so they mine both chains at the same time.

**Comment by w1g0** [comment]
In that case only the software needs to be written, distributed and promoted for adoption. Why would you want it in an ECIP?

**Comment by DonaldMcIntyre** [comment]
To do Bitcoin Merged Mining the ETC protocol has to be changed as per this ECIP-1096, so I assume it has to be changed also to use the Ethereum mining base. 

If we check the ECIP i think we could see what changes would be needed, but imma not engineer so that is done by others.

What I meant above is that neither the Bitcoin nor Ethereum protocols would need to be changed for their miners to merge mine ETC, but ETC yes.

**Comment by stevanlohja** [comment]
@martinmedina @SergioDemianLerner Is this ECIP still active? otherwise, the Issue may be closed and ECIP inactive. Just a friendly ping!
