### ISSUE TITLE
ECIP-1092

### ISSUE THREAD

**Issue by slavserver** [ethereumclassic/ECIPs#357]
Are you seriously? Now, in no case should the algorithm be changed, ECIP-1092 only (PirlGuard)! I hope you understand why this should not be done .. In the future, it is necessary to monitor ECIP-1092, I'm sure everything will be fine, and only then, gradually, you can think about changing the algorithm, at least in a year. And I am 90% sure that there will be no need to change the algorithm.

**Comment by ponchoetc** [comment]
agree LET ETC AWAY FROM ASIC miners dont want to lick chinese asic factory balls

**Comment by q9f** [comment]
duplicate of #327
