### ISSUE TITLE
https://ecips.ethereumclassic.org/networking page empty

### ISSUE THREAD

**Issue by mikeyb** [ethereumclassic/ECIPs#358]
https://ecips.ethereumclassic.org/networking loading no content.  We should investigate

**Comment by q9f** [comment]
Do we have any networking proposals at all?

**Comment by q9f** [comment]
https://ecips.ethereumclassic.org/ECIPs/ecip-1063

https://ecips.ethereumclassic.org/ECIPs/ecip-1082

**Comment by nargotik** [comment]
Shall become solved with PR #413
