### ISSUE TITLE
ECIP-1094: Integration of VeriBlock Proof-of-Proof into Ethereum Classic [51% Attack Prevention]

### ISSUE THREAD

**Issue by max-sanchez** [ethereumclassic/ECIPs#360]
The issue is the discussion for ECIP #340 which proposes to integrate VeriBlock Proof-of-Proof into Ethereum Classic for 51% attack prevention.

**Comment by gitr0n1n** [comment]
@max-sanchez Do you intend to hold a presentation on your proposal like the other 51% attack solutions? (1092, 1096, 1097, 1099, 1100)

**Comment by max-sanchez** [comment]
@gitr0n1n Yes, we are working on scheduling a presentation for the first half of next week.

**Comment by stevanlohja** [comment]
@max-sanchez Is this ECIP still active? Just a friendly ping before considering this Issue closed or ECIP inactive.
