### ISSUE TITLE
PRESENTATION - IOG (IOHK) Checkpointing (ECIP-1097)

### ISSUE THREAD

**Issue by developerkevin** [ethereumclassic/ECIPs#361]
# IOHK Checkpointing Presentation and Q&A

---

## Checkpointing Presentation (Join with [Crowdcast link](https://www.crowdcast.io/e/9epmnuoc))

IOHK (IOG) has released ECIP-1097 #347 which covers their proposed "Checkpointing" system which aims to prevent 51% attacks on ETC. They'll explain the proposal and conduct a presentation, followed by a community Q&A.

The goal of this call is simply to get contributors, community members, stakeholders and especially other teams who have created similar proposals (They implore other proposal authors @max-sanchez, @VeriBlock @Dexaran, @rsksmart, @rootstock to show up to ask as many questions as needed) to properly understand this proposal. More details to come.

- When: Friday, Sept. 4, 2020; 2PM UTC, 7AM PST, 11AM EST - 30 minute presentation followed by Q&A

- Where: Crowdcast (Link: https://www.crowdcast.io/e/9epmnuoc)

## Q&A

Questions will be submitted directly in the Crowdcast meeting (Link will be posted when date/time is confirmed)

## References

- Checkpointing Explanation Video: https://youtu.be/aasUIB1W81E
- Securing Ethereum Classic via Checkpointing:  https://youtu.be/1JeL4pAjmXM 
- Securing PoW Ledgers via Checkpointing Paper: https://iohk.io/en/research/library/papers/securing-proof-of-work-ledgers-via-checkpointing/

**Comment by Dexaran** [comment]
I would ask @creepas to join the presentation to represent ECIP 1092.
I'm unable to do so at the assigned time.

**Comment by creepas** [comment]
I will be there.

**Comment by mikeyb** [comment]
> I would ask @creepas to join the presentation to represent ECIP 1092.
> I'm unable to do so at the assigned time.

This is an IOHK presentation.  1092 would need to schedule its own presentation

**Comment by creepas** [comment]
yes it will be done we setting up time.

**Comment by TheEnthusiasticAs** [comment]
The replay of this presentation: https://www.crowdcast.io/e/9epmnuoc/1
