### ISSUE TITLE
PRESENTATION - ECIP 1092 (51 percent attack solution)

### ISSUE THREAD

**Issue by Dexaran** [ethereumclassic/ECIPs#364]
## ECIP 1092 QA session on ETC Discord

Ethereum Commonwealth proposed a solution to 51%-attack on Ethereum CLassic network: [ECIP 1092](https://github.com/ethereumclassic/ECIPs/issues/327).  Community members and ECIP 1092 supporters will represent the ECIP and answer questions.

Following the recommendations of representatives of other teams (mostly IOHK) and requests from community members, we decided to organize a live Q&A session. The goal of this call is to get contributors, community members, stakeholders and other teams who have created similar proposals to ask questions as needed to properly understand this proposal.

- When: Wednesday, Sept. 9, 2020; 2PM UTC, 11AM EST.

- Where: Crowdcast (https://www.crowdcast.io/e/t1jytfn2/register)

## Q&A

https://www.crowdcast.io/e/t1jytfn2/register

## References

- [ECIP 1092](https://github.com/ethereumclassic/ECIPs/issues/327)

- [Amendment to Nakamoto Consensus and network attack resolutions](https://gist.github.com/Dexaran/b7c23ec264019665cffd35d35bc26ee9)

**Comment by q9f** [comment]
You can host questions on sli.do or crowdcast, that might be easier to gather and answer them.

**Comment by Dexaran** [comment]
We were asked to reschedule the presentation to Wednesday 2 PM UTC. We will probably use Crowdcast platform as suggested by IOHK team.

**Comment by creepas** [comment]
https://www.crowdcast.io/e/presentation---ecip-1092

**Comment by creepas** [comment]
https://www.crowdcast.io/e/t1jytfn2/register

**Comment by creepas** [comment]
Video from presentation: https://www.youtube.com/watch?v=uqU48amiZk8&feature=youtu.be

I want to propose to move this EICP to last call.
