### ISSUE TITLE
ETC Core Devs Call 15 - ECIP-1049 Keccak Breakout Call

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ECIPs#382]
Can the ECIP editors and ECIP process participants note where the opposition to ECIP-1049 are to vocalize their opinions/opposition and have this conversation with the pro-SHA3 people to attempt to build consensus?

Reasoning for this Open Issue:
The opposition was not addressed in any of the three SHA3 conversation threads on github and the comments have not been addressed on the recent SHA3 CDC calls. Can we hold a CDC focused on addressing these consensus issues and try to resolve them prior to ECIP-1049's Oct 9th `Accepted` call? Hopefully this will prevent a chain split.

Issue threads ref:
https://github.com/ethereumclassic/ECIPs/issues/342
https://github.com/ethereumclassic/ECIPs/issues/13
https://github.com/ethereumclassic/ECIPs/issues/8
cdc ref:
https://github.com/ethereumclassic/ECIPs/issues/333
https://github.com/ethereumclassic/ECIPs/issues/362

Luke (xocel) from ETC Labs asked where to oppose the algo change in Discord after the CDC 13 call ended. It was noted that this 9/11 call was not about pro/opposing SHA3 but to decide between SHA3-256 or Keccak256 in the pro-SHA3 camp.

[xx:04 AM] xocel: how do we express opposition to both keccak256 and sha3?
[xx:05 AM] McDappas:
how do we express opposition to both keccak256 and sha3?
@xocel  I think thats a different call
[xx:05 AM] xocel: ok. cool.

I think we all want to prevent chain splits, so this feels like an important step as there are only a few weeks left until ECIP-1049 moves to `Accepted` status on Oct-9. Lastly, I see an `Accepted` ECIP can still be moved to `Rejected` status. Can someone familiar with the process explain that in-depth should ECIP-1049 move forward and there is material contention?
https://github.com/ethereumclassic/ECIPs#process-overview

Thanks,
  r0n1n

Here are some noted vocal opposition from familar names that are more technical than myself (opposition was noted in github or on discord):
- Dexaran @Dexaran https://github.com/ethereumclassic/ECIPs/issues/342#issuecomment-685208360
- Belford @BelfordZ https://github.com/ethereumclassic/ECIPs/issues/13#issuecomment-551256069
- Cody @realcodywburns (Discord discussions in `#general`)
- Luke @iquidus  (Discord discussions in `#general`)

**Comment by realcodywburns** [comment]
My key opposition is to the timing of the ecip as it should not be discussed or accepted until after the treasury is settled. This isn't a 51% attack mitigation and isn't critical to the near term success of ETC.

**Comment by gitr0n1n** [comment]
When are the authors able to attend a CDC prior to Oct 9th? I'll be happy to host if necessary to give the opposition as fair stage and allows the authors plenty of time to respond to the opposition's documented concerns. @stevanlohja @p3c-bot 

Suggested:

### ETC Core Devs Call 15

- When: Friday, October 2nd, 2020?
- Where: Discord or Crowdcast
- Focus: SHA3-256 or Keccak256 Opposition Formal Conversation

### Agenda

- Review opposition comments
- Give the authors a chance to discuss the opposition concerns
- Goal: work closer to finding consensus as suggested by the ECIP process.

**Comment by q9f** [comment]
Where have you been on the last 3 calls? It's not that we don't do calls and don't ask everyone to state their concerns.

ECIP-1049 will also be discussed on the Call 14 this Friday. You are welcome to join and raise your concerns.

**Comment by gitr0n1n** [comment]
@q9f Thank you for the offer, but it appears CDC 14 is related to 51% attacks and there likely won't be enough time to adequately address the CDC 15 topics.

The during the last 3 calls relate to ECIP-1049 the proposal has not been in a finalized state to even begin the formal opposition conversation. it likely should have been left in draft status to iron out the details, but that's okay because it is in Last Call status until at least October 9th.

Now that the ECIP-1049 is more finalized by the authors due to CDC 13. It is appropriate to have this CDC 15 conversation. You're welcome to join the conversation. I'll be moderating/recording to assure there is ample time for the authors to address the documented concerns/opposition. The author of ECIP-1049 has agreed to be present to answer the opposition on video.

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n I prepared a call platform on discord: https://discord.gg/3ZbKvb

**Comment by antsankov** [comment]
I will be there on that date, October 2nd at 4PM UTC to address questions brought up. This will be voice only, and on the discord ideally. I respect @gitr0n1n a lot for the work, entirely on his own, meticulously maintaining the ETC wikipedia page. By the end of the call we'll either see eye to eye, or at least agree to disagree. 

It's important to note that we had 2 previous calls, ETC Core Devs Call 13 (9/11/2020) and ETC Core Devs Call 12 (08/03/2020),  about the exact subject of ECIP-1049, @gitr0n1n wasn't on either of them, where I took time to prepare extensively, brought experts on, and extensively addressed all concerns brought up during the call.

**Comment by gitr0n1n** [comment]
@antsankov you've had these comments open since 2019. "I had taken time to prepare extensively, brought experts on, and extensively addressed all concerns brought up during the call." Its great to hear you're prepared for CDC 15.

To be clear why this call is being held now: You submitted to finalized this proposal's draft 5 days ago via the cited PR above. Lets keep it factual. All of us would prefer you engaged in written outlets provided so international members could participate in coverstion with you. But you've decided to require a CDC to communicate with you via voice. It's odd, but here we are honoring your special requests that no other ECIP authors request. Please note oppositon in the formal GitHub threads is just as valid as vocal opposition on the CDC's.

I look forward to October 2nd as do many of the documented opposition since 2019 when you originaly proposed this idea. Thanks for finally agreeing to have the conversation and acknowledge the opposition to this proposal.

**Comment by ponchoetc** [comment]
I support this, i cant see any dev count miners opinion and its sad because its supossed that ethereum classic is democracy but it seems is not Miners don't support algo change, better improve solutions in core and leave the algo alone

**Comment by stevanlohja** [comment]
> I support this, i cant see any dev count miners opinion and its sad because its supossed that ethereum classic is democracy but it seems is not Miners don't support algo change, better improve solutions in core and leave the algo alone

The PoW algorithm is "core"...

**Comment by TheEnthusiasticAs** [comment]
@gitr0n1n Would you please add the "Where" - https://discord.gg/Ue2sJm6 - and the "When" to your first post!? Thank you.

**Comment by q9f** [comment]
Do you mind if we rename it to: _ETC Core Devs Call 15 - ECIP-1049 Keccak Breakout Call_?

**Comment by q9f** [comment]
I won't be able to attend the call on Friday, unfortunately, but I want to raise concerns that block 12 million activation is way too fast and should be carefully coordinated with the client developers.

**Comment by gitr0n1n** [comment]
> I won't be able to attend the call on Friday, unfortunately, but I want to raise concerns that block 12 million activation is way too fast and should be carefully coordinated with the client developers.

Noted, I'll vocalize this concern for you @q9f , same as i will vocalize a view other comments due to people not being able to attend the call.

I hope we have people on the call that can vocalize for themselves. But I understand how some are not native English speakers and prefer to communicate via ECIP. It's the goal to not penalize them for being unable to communicate via audio.

**Comment by gitr0n1n** [comment]
> Do you mind if we rename it to: _ETC Core Devs Call 15 - ECIP-1049 Keccak Breakout Call_?

No I don't mind that. Let me do that real quick.

**Comment by developerkevin** [comment]
Not sure this counts as a core devs call as majority of the core devs don't plan on showing up and plus this is not lead by the hard fork coordinator. It's essentially just a call created by a volunteer to voice his opposition to Keccak256.

**Comment by wpwrak** [comment]
For the record, let me repeat something I proposed a while back on discord: given that ECIP-1049 is now being mainly justified as being an anti-51% measure, and that we have 1) ECIP-1099 coming, which will provide a) a band-aid and b) is expected to substantially increase ETC hash rate over the next months, plus 2) it seems that MESS will be deployed as a specific anti-51% measure, the 51% risk may reduce dramatically.

Considering that ECIP-1049 is likely to drive away most of the current ETC miners, and is criticized by many, it would therefore be advisable to refrain from rushing any commitment to ECIP-1049 deployment. Specifically, I'd suggest to defer the decision of whether to move ECIP-1049 to "Accepted" until March 2021. By that time, we will know i) whether ECIP-1099 will have resulted in the return of current 4 GB ETC miners, who will be briefly excluded by the DAG crossing 4 GB before ECIP-1099 activates, ii) whether 3 GB miners will have returned to ETC, and iii) whether the 4 GB crossing of ETH that is expected to occur in December 2020, will have resulted in 4 GB miners previously mining ETH to switch to ETC. Furthermore, we will iv) have a few months of operational experience with MESS.

If the turnout of i) through iii) should be low, and possibly iv) be unsatisfactory, the proponents of ECIP-1049 would have a far easier time to justify the need for such a major change to the ETC ecosystem, and avoid further conflict or even a split of ETC into competing coins.

Note that anyone planning to make ASICs for ECIP-1049 should be largely unaffected by delaying this decision. They can perform the steps that require minimum investment, i.e., the design of the chip logic, and even backend, and still have enough time to start the capital-intense production and have their chips ready for the projected introduction date of ECIP-1049 if such a switch should be decided in March 2020.

**Comment by wpwrak** [comment]
I'd also like to repeat another idea: most if not all of the conflict surrounding ECIP-1049 stems from it proposing the replacement of a key part of the ETC infrastructure, the PoW algorithm, in a way that is incompatible with the continued economic viability of current ETC mining hardware.

A way to avoid forcing current ETC miners out of the ecosystem they have been supporting so far would be to start ECIP-1049 on a new coin (how about ETK ? K and C are often considered the same sound, and K would stand for Keccak.), and let ETC continue as before. The rules for ETK, including the allocation of initial assets, could be defined to the liking of its creators, and they could also define a schedule for launch and operation without any need to coordinate with the ETC community. ETC and ETK could (and should) still remain strong ties, e.g., EVM compatibility, and if ETK turns our to be superior, people could switch from ETC to it on their own volition, without the trauma of a forced migration.

Adopting this approach would remove the ECIP-1049 controversy from ETC and ETK, and make room for issues that should perhaps be more important for the future of ETC/ETK, e.g., the development of attributes that will make people want to choose ETC/ETK over, say, ETH, or other coins.

**Comment by gitr0n1n** [comment]
Recording of ETC Core Devs Call 15: https://vimeo.com/464336957

**Comment by gitr0n1n** [comment]
Please direct future commentary to the 1049 discussion thread:

https://github.com/ethereumclassic/ECIPs/issues/13

Thanks for the productive call!

**Comment by developerkevin** [comment]
This mining algorithm change has never been touted as a solution against 51% attacks. It's impossible to solve against such attacks. It instead helps mitigate such attacks by making ETC the "apex predator" in the Keccak/SHA3 realm. This algo change would benefit the network in many ways such as faser node validation, faster sync times, and more efficient mining. GPUs would still be able to mine SHA3/Keccak, as would FPGAs. However, to again reiterate, Keccak was never meant to solve 51% attacks.

**Comment by gitr0n1n** [comment]
"This mining algorithm change has never been touted as a solution against 51% attacks." - @developerkevin
> A response to the recent double-spend attacks against Ethereum Classic.
Source: https://ecips.ethereumclassic.org/ECIPs/ecip-1049

"This algo change would benefit the network in many ways such as faser node validation, faster sync times, and more efficient mining. GPUs would still be able to mine SHA3/Keccak, as would FPGAs." - @developerkevin

Many of your talking points were discussed during the call. Please listen to the CDC 15 call to learn about all the negative externalities of the ECIP-1049 proposal. Thanks!
Source: https://vimeo.com/464336957
