### ISSUE TITLE
Presentation - Modified Exponential Subjective Scoring for Ethereum Classic (ECIP-1100)

### ISSUE THREAD

**Issue by q9f** [ethereumclassic/ECIPs#383]
### Presentation by the "Artificial Finality" Working Group

- When: **Wednesday - Sept. 23, 2020 - 2PM UTC**
- Where: Crowdcast https://www.crowdcast.io/e/mess-classic-ecbp-1100
- Agenda
  - Overview "Artificial Finality" and non-invasive 51-percent-protection
  - Quick explanaition of the "MESS" protocol (ECIP-1100)
  - LIVE Demo on the MESS testnet using Geth
  - Community Q&A session
- Presenters
  - @meowsbits (working group)
  - @ausiv (working group)
  - @bobthegrownup (session moderator)

### Abstract
@etclabscore, in consultancy with @openrelayxyz and @chainsafe, develop and propose a finality algorithm called MESS for Ethereum Classic that, if adopted by the honest majority, would raise chain state finality near-exponentially with negligible risk of network bifurcation.

### Motivation
A low hashrate has caused Ethereum Classic's consensus algorithms to yield inconvenient and undesirable finality rates. ECIP-1100 "MESS" offers a way to increase the finality rate without tampering with existing "hard" chain consensus functions or characteristics, and to do so with minimal negative side effects.

- Proposal: [ECIP 1100: MESS (Modified Exponential Subjective Scoring)](https://ecips.ethereumclassic.org/ECIPs/ecip-1100)
- Read more: [Agreeing To Disagree: Proposing a Weakly-Subjective Finality Solution for Ethereum Classic](https://medium.com/etc-core/agreeing-to-disagree-proposing-a-weakly-subjective-finality-solution-for-ethereum-classic-7daad47efc0e)
- Discussion: #374 
- Bonus: [MESSnet TV](https://mess.canhaz.net) - Visualization of an ad-hoc Classic testnet implementing MESS.

_We encourage all parties, especially other ECIP authors, to participate and ask questions._

**Comment by meowsbits** [comment]
I just updated the proposal, check it out! https://github.com/ethereumclassic/ECIPs/pull/384

**Comment by q9f** [comment]
Recording https://www.crowdcast.io/e/mess-classic-ecbp-1100
