### ISSUE TITLE
Broken link in ECIP-1043

### ISSUE THREAD

**Issue by mvandemar** [ethereumclassic/ECIPs#393]
In ECIP 1043: Fixed DAG limit restriction there is a link with the anchor text of "Superseded by | 1099" (technically only the "1099" is hyperlinked). It points to a 404 due to a typo. The url of the landing page is missing the "c" in "ecip":

`https://ecips.ethereumclassic.org/ECIPs/eip-1099`

It should be:

`https://ecips.ethereumclassic.org/ECIPs/ecip-1099`

**Comment by nargotik** [comment]
PR #413 to solve this issue
