### ISSUE TITLE
ECIP-1099 critical bug in reference code

### ISSUE THREAD

**Issue by biospb** [ethereumclassic/ECIPs#397]
Hello

Recently I tried to add this ECIP support to ethminer and found that reference code provided in this ECIP probably contains a bug in seedHash(block) function. It results in DAG rebuild every 30000 blocks, having the same size and epoch number!

Lets see: block number / old epoch / new epoch / seed cycles
11700000 / 390 / 195 / 390
11730000 / 391 / 195 / 391 <--- BUG. Is it supposed to be 390 ?
11760000 / 392 / 196 / 392

Geth has different implementation so DAG remains the same across all 60000 blocks.

If this really a bug the reference code of this function should be like this

```
func seedHash(block uint64) []byte {
  seed := make([]byte, 32)
  if block < oldEpochLength {
    return seed
  }
  // keep using oldEpochLength here so seeds don't overlap
  **// use epoch number to keep seed constant for entire epoch**
  keccak256 := makeHasher(sha3.NewLegacyKeccak256())
  for i := 0; i < int(**calcEpoch(block)*calcEpochLength(block)**/oldEpochLength); i++ {
    keccak256(seed, seed)
  }
  return seed
}
```

Otherwise the bug is in Geth

**Comment by bobsummerwill** [comment]
CC @iquidus @q9f

**Comment by iquidus** [comment]
There may be some confusion here, the original seedHash function left room for inconsistencies, some areas called seedHash simply by passing a blocknumber (any blocknumber), where elsewhere an epoch boundary was always being passed, (epoch*epochLength+1). These inconsistencies resulted in a bug for the second half of a new epochs. This was addressed in the last core-geth release, refactoring seedHash to avoid this kind of inconsistent usage (now accepts an epoch and an epochLength and calculates the block). https://github.com/etclabscore/core-geth/blob/master/consensus/ethash/algorithm.go#L143


Side note: this fork of ethminer https://github.com/etclabscore/ethminer works post thanos.
