### ISSUE TITLE
ECIP 1000: Nominate new ECIP Editors

### ISSUE THREAD

**Issue by q9f** [ethereumclassic/ECIPs#401]
To prevent the Ethereum Classic governance from halting, please use this ticket to nominate candidates for the ECIP Editor position.

Ideally, we need at least two more ECIP editors. An ideal candidate should be well-recognized in the Ethereum Classic community and widely acting independently.

Everyone can nominate themselves or other community members. Nominations have to be accepted by the nominees and approved by the existing (and/or past) ECIP editors.

**Comment by faraggi** [comment]
What are the editor responsibilities exactly? What's to be expected of them on a regular basis?

**Comment by TheEnthusiasticAs** [comment]
> What are the editor responsibilities exactly? What's to be expected of them on a regular basis?

here are the infos https://github.com/ethereumclassic/ECIPs

**Comment by stevanlohja** [comment]
Since Yaz is no longer an editor, I nominate myself to represent Coop. At least 1 volunteer from Coop, IOHK, Labs, and independents would be sweet!

@faraggi ECIP editor is simply a volunteer role to make sure proposals are formatted correctly, assign a proposal and ecip numbers before merging, and follow up with the proposal author. It's a no-judgment role simply paper-pushing.

**Comment by gitr0n1n** [comment]
> Ideally, we need at least two more ECIP editors. An ideal candidate should be well-recognized in the Ethereum Classic community and widely acting independently.

As one of the active `independent` contributers, I'd be happy to help secure the Ethereum Classic governance as one of the ECIP Editor positions. You can review my commits throughout this github organization to gauge value added contributions. I typically check once a week to clear any PRs in the ethereumclassic.org repo, So this wouldn't be too much of an additional burden to help review/process the ECIP procedural formalities.

@TheEnthusiasticAs is also quite active and would be a great `independent`  addition.

**Comment by TheEnthusiasticAs** [comment]
I am for @stev & @gitr0n1n. Their contributions you know already. Also, with the time @faraggi from IOHK could join too after he is learned more by the ETC participants.

I would gladly help, but I am already taking care of PRs/issues for the Ethereum Classic website, admin/mod/communication works on several social media channels alongside to my day job.

**Comment by gitr0n1n** [comment]
To familarize myself with who is currently an ECIP editor: @q9f do you have two controlled accounts approved in here?

So we only have 4 editors with one leaving (Cody)? So 3 active editors?

https://github.com/orgs/ethereumclassic/teams/ecip-editors

**Comment by TheEnthusiasticAs** [comment]
@DirtyRusski, is known in the Ethereum Classic  discord for long time now, could support as an independent contributor, too. He is active in mining, general blockchain topics channels there

**Comment by faraggi** [comment]
I'll be glad to take on this role and be a representative for IOHK.
However, I somewhat agree with @TheEnthusiasticAs  and I don't want to hurry the decision.
So, if needed, I can come back to this conversation in some weeks and

**Comment by kizoojun01** [comment]
kizoojun01

**Comment by bobsummerwill** [comment]
It would be good to get IOHK actively involved in the ECIP process.
And Stev has my support, of course.

**Comment by q9f** [comment]
I saw the following nominations, please each nominee respond with a statement accepting or rejecting the nomination before moving on with this:

* @TheEnthusiasticAs _independent nominee_
* @gitr0n1n _independent nominee_
* @stevanlohja ETC Cooperative
* @faraggi IOHK/PegaSys
* @DirtyRusski _independent nominee_
* @kizoojun01 _independent nominee_

Please do so by end of week so we can transition to 2021 with a new team of editors.

> To familarize myself with who is currently an ECIP editor: @q9f do you have two controlled accounts approved in here?
> 
> So we only have 4 editors with one leaving (Cody)? So 3 active editors?
> 
> https://github.com/orgs/ethereumclassic/teams/ecip-editors

This has to be cleaned up once we updated ECIP 1000. I hope Cody will be available to assist in this transition.

**Comment by DirtyRusski** [comment]
I don't have much experience with github, but I am willing to learn. If someone is more qualified than me, (which I'm sure there is) I believe that person should get the editor position. But thank you for the consideration, it means a lot to me.

**Comment by TheEnthusiasticAs** [comment]
As stated previously, due to the time limit, I am rejecting

**Comment by faraggi** [comment]
I accept the _nomination_. 
Current editors can make the decision on timing for my acceptance/denial.

@q9f  For clarification, I will be representing IOHK and not Pegasys.

**Comment by mikeyb** [comment]
One consideration is that the Editors also has Admins role in this Org.  I do not think we should be applying a group like this to an Admin role.  We should consider setting the Editors group as 'Maintain' Role and only add individual users as Admin role.

Thoughts?

![image](https://user-images.githubusercontent.com/36461/101811157-f4d5d980-3ad6-11eb-923e-55afcf1d31ec.png)

**Comment by stevanlohja** [comment]
> One consideration is that the Editors also has Admins role in this Org. I do not think we should be applying a group like this to an Admin role. We should consider setting the Editors group as 'Maintain' Role and only add individual users as Admin role.
> 
> Thoughts?
> 
> ![image](https://user-images.githubusercontent.com/36461/101811157-f4d5d980-3ad6-11eb-923e-55afcf1d31ec.png)

Definitely, it's a _maintaining_ role-specific to the repo after-all.

**Comment by q9f** [comment]
> Thoughts?

That's basically what you just described. There is an owner (Cody) and the ECIP Editors (Admins) who can maintain this repository.

I see 2 accepted nominations, one rejected, and 2 not giving any statement yet. Last call till Friday @stevanlohja @gitr0n1n 

I'll create PRs for @faraggi and @DirtyRusski

**Comment by stevanlohja** [comment]
Confirmed I accepted being ECIP editor

**Comment by gitr0n1n** [comment]
Confirmed I accepted being ECIP editor

**Comment by gitr0n1n** [comment]
> I don't have much experience with github, but I am willing to learn. If someone is more qualified than me, (which I'm sure there is) I believe that person should get the editor position. But thank you for the consideration, it means a lot to me.

I'll train you up. It's quite easy to learn. You'll be great at this role.

**Comment by gitr0n1n** [comment]
@q9f whats the status of this issue? Do stev and I need to start contributing as editors. Please ping so I know to check the ECIP repo more frequently for any open tasks/housekeeping. Thanks.

**Comment by q9f** [comment]
Thanks everyone. I'll merge them backwards so I have enough approvals for each of the PRs.

**Comment by q9f** [comment]
Welcome @faraggi @DirtyRusski @stevanlohja @gitr0n1n and thanks for stepping up.

**Comment by developerkevin** [comment]
Lately I've noticed quite a lag in approving some of the pull requests that need approval so we can move forward. This seems to create a sort of backlog PRs and/or issues. 

I'd nominate myself to be an editor and create a PR if there's still a need for another one, though the proposed editor additions PRs still need to be approved by two.

**Comment by DirtyRusski** [comment]
> Lately I've noticed quite a lag in approving some of the pull requests that need approval so we can move forward. This seems to create a sort of backlog PRs and/or issues.
> 
> I'd nominate myself to be an editor and create a PR if there's still a need for another one, though the proposed editor additions PRs still need to be approved by two.

I will gladly resign my nomination to give you the opening. It looks like I will be quite busy with school this semester anyways and only want what is best for the ETC community/project

**Comment by developerkevin** [comment]
@DirtyRusski I'm unaware of any rules preventing more than a certain amount of members to become a “editors.”
