### ISSUE TITLE
ECIP 1103: Magneto EVM and Protocol Upgrades

### ISSUE THREAD

**Issue by q9f** [ethereumclassic/ECIPs#412]
ref #411 

> _Enable the outstanding Ethereum Foundation _Berlin_ network protocol upgrades on
the Ethereum Classic network in a hard-fork code-named _Magneto_ to enable
maximum compatibility across these networks._

**Comment by TokenHash** [comment]
At first glance this hard fork proposal seems uncontroversial.

**Comment by TokenHash** [comment]
At second glance it seems the Berlin hard fork is not implemented in Ethereum: https://twitter.com/JHancock/status/1351519606590955522?s=20

So, it seems a non-urgent hard fork for ETC, especially when considering there are historic proposals native to ETC that seem to have higher priority. Such proposals are:

- Keccak 256
- Proto Treasury
- Flyclient
- NiPoPoWs
- Checkpointing

On the other hand hard fo4king every six months is not advisable for any base layer chain.

**Comment by stevanlohja** [comment]
The proposal needs to be substantiated with a roadmap and strategy pertaining to ETC other than merging ETH changes - again.

**Comment by gitr0n1n** [comment]
> The proposal needs to be substantiated with a roadmap and strategy pertaining to ETC other than merging ETH changes.

I haven't seen that as a requirement for submitting an ECIP. Please cite in the ECIP-1000 where it mentions this requirement. Thanks!

**Comment by q9f** [comment]
I'm happy to collaborate on a roadmap if anyone wants to champion this. Not really relevant for this proposal though. Having the protocol updated to the latest version is the least we can do unless we want to developers to use xDAI or Binance Chain instead.

**Comment by slavserver** [comment]
won't you all calm down? ))

**Comment by meowsbits** [comment]
- Parity. In order for this proposal to match the [Berlin Network Upgrade Specification](https://github.com/ethereum/eth1.0-specs/blob/master/network-upgrades/berlin.md) it (now) needs to [remove EIP-2315](https://github.com/ethereum/go-ethereum/pull/22414). 

- Timelines. I assume that the block numbers in the spec are intended tentatively. Ethereum is aiming for an ETH mainnet activation at `12_244_00` (14 Apr 2021), and this spec proposes "May 2021" for ETC mainnet activation. For the sake of conservative risk management I propose targeting a minimum of 45-60 days behind the intended ETH activation.

**Comment by meowsbits** [comment]
We have some cross-client tests generated including the Magneto configuration.
I have them as a WIP PR here: https://github.com/etclabscore/tests/pull/4. Still under development and review, so don't treat them as a concrete reference just yet, but should be good for starters.

Generated/filled tests are extrapolated from the standard https://github.com/ethereum/tests suite, with CoreGeth filling additional tests for Ethereum Classic fork configurations using Ethereum-canonical fork configurations as reference for Pre-State and Transaction parameters (in the case of the GeneralStateTests). 

Test generation has been done on top of the latest version pegged by ethereum/go-ethereum v1.10.1 at https://github.com/ethereum/tests/tree/c600d7795aa2ea57a9c856fc79f72fc05b542124.

**Comment by drospa** [comment]
@q9f can you also add that Mantis (maintained by IOHK) will support this HF but at a later state than the proposed 13_189_133 on ETC PoW-mainnet (July 21st, 2021)?

**Comment by Nenginyo** [comment]
`0xa40dfee99e1c85dc97fdc594b16a460717838703`
