### ISSUE TITLE
Please update ECIP Editor's to `Write Access`

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ECIPs#414]
For some reason my permission aren't configured correctly. Will you resolve this issue other ecip editors? Thanks in advance.

Current ECIP editors:

Mr. Meows D. Bits ( @meowsbits )
Talha Cross ( @soc1c )
Zachary Belford ( @BelfordZ )
Felipe Faraggi ( @faraggi )
r0n1n ( @gitr0n1n )
Stevan Lohja ( @stevanlohja )
https://ecips.ethereumclassic.org/ECIPs/ecip-1000

I think this needs updating too:
https://github.com/orgs/ethereumclassic/teams/ecip-editors
@ethereumclassic/ecip-editors

**Comment by q9f** [comment]
the only users with permission to update the teams are @elaineo @mikeyb @realcodywburns

**Comment by gitr0n1n** [comment]
> the only users with permission to update the teams are @elaineo @mikeyb @realcodywburns

Thanks for the reponse. Are these users still active with the project?

**Comment by gitr0n1n** [comment]
It appears the error is I don't have "write access". It looks like @bobsummerwill mentioned this problem a while back. Can we get a resolution on this to get the ECIP process is functioning in proper order?

https://github.com/ethereumclassic/ECIPs/pull/404#issuecomment-770467022

**Comment by realcodywburns** [comment]
conversation to >> https://github.com/orgs/ethereumclassic/teams/ecip-editors/discussions/1

**Comment by realcodywburns** [comment]
assign issues to me that need my attention. repo access rights follow role based access control.  : 
the ecip editors team has admin access. 
website marketing team has maintenance role
all others have read

**Comment by gitr0n1n** [comment]
Thanks Cody.

**Comment by gitr0n1n** [comment]
It looks like the ECIP editors perms were added. The issue can be closed.
