### ISSUE TITLE
Kevin's ECIP Editor Permissions

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ECIPs#415]
It looks like @developerkevin has ECIP Editor permissions, but is not listed in the ECIP-1000. Can we get that updated?

**Comment by q9f** [comment]
he is not ecip editor, he inherited the permissions from another role in the ethereumclassic github organization.

only @elaineo @mikeyb @realcodywburns have permissions to modify teams and roles as far as I can see.

**Comment by gitr0n1n** [comment]
> he is not ecip editor, he inherited the permissions from another role in the ethereumclassic github organization.
> 
> only @elaineo @mikeyb @realcodywburns have permissions to modify teams and roles as far as I can see.

If Kevin not an ECIP editor, why is @developerkevin approving and merging PRs in this repo? Isn't that a vilation of the ECIP process?

**Comment by gitr0n1n** [comment]
After digging a bit more, it looks like @developerkevin might be an ECIP editor?

https://github.com/ethereumclassic/ECIPs/pull/403#issuecomment-771976537

**Comment by realcodywburns** [comment]
the web marketing team has 'maintain' access to this repo because they maintain ecips.ethereumclassic.org from here. If the editors are active in maintenance of the website side of it as well as the ecip procedure side happy to remove that teams access.

..... the website team should know better than to merge ecips .....

**Comment by gitr0n1n** [comment]
> the web marketing team has 'maintain' access to this repo because they maintain ecips.ethereumclassic.org from here. If the editors are active in maintenance of the website side of it as well as the ecip procedure side happy to remove that teams access.
> 
> ..... the website team should know better than to merge ecips .....

Thanks for the explanation @realcodywburns . I'll close this issue.

cc: @developerkevin
