### ISSUE TITLE
[Discussion] ECIP 1104: Dark Mode

### ISSUE THREAD

**Issue by meowsbits** [ethereumclassic/ECIPs#417]
`Discussions-to` target for https://github.com/ethereumclassic/ECIPs/pull/416.

**Comment by meowsbits** [comment]
Personally I'm in favor this. I find it clearly innovative, relevant, and firmly in line with the foundational principles of the network and community. 

I must admit to a small concern with the color candidates proposed for the democratic nomination. Despicable, pallid, mute, lifeless tones. I would urge the community to consider more vital and expressive hues like 
- the warm and earthy #060a09
- a timelessly modern #0f0f1a
- an austere, but comfortable #120f0f
 
Although I am sure I could offer at least 46 further alternatives superior to what my obviously style-less colleague has offered, it occurs to me that the voting procedure might stake a bold claim toward democracy and its better brother, anarchy, if the voting contract were to allow for _arbitrary hex encoded values_ to be submitted, and then for those submissions to be averaged to derive the final collective result. 

In order to best mediate this frontier democracy, I further propose that the theoretical contract weight the bespoke votes by an associated ETC stake (sums obviously reclaimable in their original total by their senders after voting is finalized). A specification for this might be taken almost verbatim from the p-ECTS proposal; though in the original, this specification requires 1/3 of the total supply of ETC to be staked to achieve a quorum (Page 3, _Parameters_ `proposalMinQuorum`), I would suggest reducing this parameter to a more modest 1/300000000 of the total supply in this case.<sup>[1](1)</sup>

Please find below additional references related to _sensible_, and informed, color choice.
- https://uxdesign.cc/githubs-dark-mode-is-too-dark-f6ab415cd4d4

[1] Total supply of Ethereum Classic at Thu Apr  1 16:00:41 CDT 2021 estimated by https://coinmarketcap.com/currencies/ethereum-classic/ is __116,313,299 ETC__. 
- 1/3 of this would be 38,771,100 ETC (roughly $530,776,000 USD)
- 1/300000000 would be 0.387711 ETC (roughly $5.31 USD)

**Comment by iquidus** [comment]
Your 'style-less' accusations are completely unfounded, and highly hypocritical but I do not wish to get off topic. 

I like the _arbitrary hex encoded_ suggestion, it provides a solid but flexible foundation for many theme based decisions moving forward.

I second 1/300000000 (0.387711 ETC). A lower barrier to entry will likely result in greater participation, diluting any potential attempts at manipulation by a malicious party.

**Comment by meowsbits** [comment]
I'm changing my opinion on the _arbitrary hex code_ feature. It's too generic. 

There's no way we need to be supporting  every possible thematic change just because your wimpy eyes hurt. If you want dark mode you can wear sunglasses like the rest of us. 

Will your magic thematic changes support Explorer? Will Explorer support you?  Does Solidity support CSS named colors? If not, why not. We need to consider the ecosystem, and we need due diligence, more developers, and we need about 14 more roadmaps than you have proposed thus far.

**Comment by iquidus** [comment]
After more thought, I'm inclined to agree, however for different reasons. An average would likely result in a mediocre mid-range color with no ability to contrast well for text. It may also result in a worse outcome than present, (e.g pink on white).

Although yes, this does affect me more due to my wimpy eyes, It is improbable that I am the only wimpy-eyed user on the network. Sunglasses are fine for some time, however their arms are often too thick, making them uncomfortable with headphones during those long ETC sessions.

The _magic_ thematic changes will support anything that supports RGB, allowing users to sync their keyboard/pc and router lighting with the ETC dark mode theme. This will be detailed more in roadmap 12.

**Comment by meowsbits** [comment]
Well since you've agreed, you unfortunately leave me no recourse but to disagree.

Here's my new counter-counter-offer. 

The specification should propose one dark color as the single specification. The determination of which specific color should be the natural consequence of the generally-considered democratic capacity to bribe the necessary ECIP Editors for the allowance to author changes to the document with exclusivity. I think this is likely the most robust and natural form of decision making we have available to us. 

Inexorably Yours,
Mr. Official Meows, Editor (accepting ~~bribes~~ donations at `0xa220e990cfC3Abe8b2E20582C3FE7b30a8b05c39`)

**Comment by iquidus** [comment]
Although ~~bribes~~ donations are a natural part of any functioning governance, I feel this would extend the ECIPs Editors powers far beyond their original scope. We might be ok with the current editors having this power, but how can we be certain it will not be abused by future editors?

I counter with the following.

A tax is introduced to block rewards (while maintaining the current ecip-1017 emission schedule), the proceeds of which will be managed by a treasury that will oversee the construction of a Colosseum. A series of battle royal events will then be hosted, any members of the community, editor or not, can volunteer to enter. The winner (appropriately titled "The Chad") determines the specific color to use. These events can be cyclical every n years to ensure the color is always updated to reflect the opinion of the baddest mf in the community (The Chad), who not only gets to choose the color in question, but also manages all funds held by the treasury until the next battle royal season.

The funds use are restricted to 

1. Maintaining the colosseum
2. hosting the battle royal events
3. personal expenses of The Chad. 

This is to ensure the funds are appropriately used for governing something this vital, and not siphoned off to less important areas of the network.
