### ISSUE TITLE
ETC Core Devs Call 17: Magneto Upgrade

### ISSUE THREAD

**Issue by q9f** [ethereumclassic/ECIPs#424]
# ETC Core Devs Call 17
* When: **Friday, May 21, 2021, 3pm UTC,** 60 minutes max
* Where: [Zoom, Meeting ID: 872 0019 5219](https://us02web.zoom.us/j/87200195219)
* Focus: Magneto Protocol Upgrade.

### Agenda

* Quick client teams check-in 
* [ECIP 1103](https://ecips.ethereumclassic.org/ECIPs/ecip-1103) Magneto Protocol and EVM Upgrades (Draft)
  * Gas Costs and Repricing
  * Transaction Envelopes and Access Lists
  * Upgrade Timing and Block Numbers #425

### Schedule A

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_835_521 | 2597580 | 15 | 4_008_693 | 2021-06-09
4_205_235 | 3807180 | 15 | 4_459_047 | 2021-06-23
12_713_732 | 6226320 | 13 | 13_192_679 | 2021-07-21

    * Mordor Testnet in four weeks
    * Kotti Testnet in six weeks
    * Ethereum Classic mainnet in ten weeks

### Schedule B (accelerated)

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_916_709 | 1026180 | 15 | 3_985_893 | 2021-06-02
4_258_403 | 1648920 | 15 | 4_368_634 | 2021-06-09
12_784_531 | 5259720 | 13 | 13_189_133 | 2021-07-21

    * Mordor Testnet asap
    * Kotti Testnet in three
    * Ethereum Classic mainnet in nine weeks

_All fork times est. at 12pm UTC_

**Comment by DonaldMcIntyre** [comment]
Are all client teams invited to this call or is it only a Core-Geth decision option?

**Comment by q9f** [comment]
All teams. Everyone.

**Comment by GregTheGreek** [comment]
Will be in attendance.

**Comment by bobsummerwill** [comment]
I am afraid that I am likely unable to attend the call tomorrow, but just wanted to register my support and ETC Coop's support for the Magneto HF, given the recent disclosure.

https://blog.ethereum.org/2021/05/18/eth_state_problems/

**Comment by q9f** [comment]
Proposing two schedules for the meeting:

### Schedule A

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_835_521 | 2597580 | 15 | 4_008_693 | 2021-06-09
4_205_235 | 3807180 | 15 | 4_459_047 | 2021-06-23
12_713_732 | 6226320 | 13 | 13_192_679 | 2021-07-21


### Schedule B (accelerated)

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_916_709 | 1026180 | 15 | 3_985_121 | 2021-06-02
4_258_403 | 1648920 | 15 | 4_368_331 | 2021-06-09
12_784_531 | 5259720 | 13 | 13_189_124 | 2021-07-21

**Comment by q9f** [comment]
Meeting concluded with rough consensus on activating schedule B:

block_now | time_to_fork | block_time | fork_block | fork_date
--- | --- | --- | --- | ---
3_916_709 | 1026180 | 15 | 3_985_893 | 2021-06-02
4_258_403 | 1648920 | 15 | 4_368_634 | 2021-06-09
12_784_531 | 5259720 | 13 | 13_189_133 | 2021-07-21

And moving to ECIP 1103 to "last call" with review period end on June 4th, 2021.

Attendants:
* Afri Schoedon
* Antoine Toulme
* Bob Summerwill
* Chris Ziogas
* David R
* Diminik Zajkowski
* iquidus

**Comment by developerkevin** [comment]
Hey going forward I think we need more transparency around these meetings. It’s not like these are just “afternoon tea” calls. I understand that you @q9f organized this well in advance, but I think it’s important we give all contributors the opportunity to be present. 

Ethereum ACD meetings are good examples of how such calls are handled. I am more than willing to facilitate and record the meetings as well as take down and publish any notes, and recordings, and set up possibly live streams. 

Anybody not in the ETC GitHub were likely unaware about today’s meeting and did not attend. If at all a possible please ping me or let me know @q9f. ✌🏼

**Comment by q9f** [comment]
I have a meeting recording and can share if it you wish to publish it

**Comment by w1g0** [comment]
> I have a meeting recording and can share if it you wish to publish it

Yes, please.

**Comment by q9f** [comment]
You should be able to download it here if you want to mirror it.

> Topic: ETC Core Devs Call 16: Magneto Upgrade
> Start Time : May 21, 2021 04:59 PM
> 
> Meeting Recording:
> https://us02web.zoom.us/rec/share/hqYEcuQ0saf_mIeCornNggseklSbPr_hYE-zGDzz4lUjvYKYr4f3lcJ8T5DSe79z.-vGWIWc2BeCtYliY
