### ISSUE TITLE
[Meeting] ETC Call 16 - Preliminary proto-treasury meeting

### ISSUE THREAD

**Issue by stevanlohja** [ethereumclassic/ECIPs#426]
# ETC Call 16
**Topic**: Preliminary proto-treasury meeting

**Motivation**: The intention of this meeting is to bring together ETC teams and the community to participate in the discussion of the proto-treasury proposal described in[ ECIP-1098](http://ecips.ethereumclassic.org/ECIPs/ecip-1098).  Feedback, debate, or constructive criticism is welcome. This is not intended to be a consensus-defining meeting, rather a great time for input and collaboration.

**Agenda**:
- Introduce yourself and/ or your team.
- Open discussion on the treasury proposal

**Time & Date**: May 12, 15:00 UTC
**Duration**: 1.5 hours (max)
**Location**: [ETC Discord ](https://discord.gg/hQs894U)(voice channel)

**Recording**: https://youtu.be/DKGX3hrZkO4

**Resources**:
- https://ecips.ethereumclassic.org/ECIPs/ecip-1098
- https://www.crowdcast.io/e/mantis
- https://youtu.be/aO1S6MOrZcE
- https://etherplan.com/2020/08/14/why-ethereum-classic-should-not-create-a-treasury/12384/
- https://etccooperative.org/posts/2021-12-03-why-treasury
- https://etherplan.com/2021/01/15/final-comments-about-the-ethereum-classic-proto-treasury-proposal/14962/
- https://medium.com/ethereum-classic-labs/treasury-proposal-for-ethereum-classic-conscientious-concerns-79cc6834da2d
- https://etccooperative.org/posts/treasury-polls
- https://github.com/input-output-hk/etc_treasury_system

**Comment by drospa** [comment]
This is the current GH repo for the smart contracts https://github.com/input-output-hk/etc_treasury_system

**Comment by gitr0n1n** [comment]
I attempted to join the server to participate in this call as I am fond of a decentralized form of a treasury, but my account is still banned in Discord from @developerkevin 's December mod rage.  I would have appreciated the ability to participate in this proposal for the development team EthereumCore and as the custodian to all of Ethereum Classic domain assets (aside from the .org DFG bought). Hopefully one of the mods can clean up the censorship on my discord account.

**Comment by bobsummerwill** [comment]
What is your Discord handle (including number), @gitr0n1n?
Let's get this resolved.

**Comment by gitr0n1n** [comment]
> What is your Discord handle (including number), @gitr0n1n?
> Let's get this resolved.

gitr0n1n #4505

**Comment by gitr0n1n** [comment]
Thanks, my discord account has been restored from the January censoring by @developerkevin 👍
