### ISSUE TITLE
ETC Core Devs Call 18

### ISSUE THREAD

**Issue by atoulme** [ethereumclassic/ECIPs#434]
# ETC Core Devs Call 18

* When: Friday, Aug 20, 2021, 3pm UTC, 60 minutes max
* Where: Zoom Meeting ID: 892 5819 4276 Passcode: 544703

## Agenda
* Quick client teams check-in
* [Mystique hard fork](https://github.com/ethereumclassic/ECIPs/issues/432)
* [ECIP-1049 work with Core Geth](https://github.com/etclabscore/core-geth/pull/369#issuecomment-892844306)
* eth/66 support

**Comment by atoulme** [comment]
Thanks fixed!

**Comment by Econymous** [comment]
I'll try to join

**Comment by tvinhas** [comment]
How do I apply to be a developer?

**Comment by stevanlohja** [comment]
@atoulme Do you have a meeting recording?

**Comment by w1g0** [comment]
https://us02web.zoom.us/recording/detail?meeting_id=%2Fvm5q9yfSruCWgaK67NgBg%3D%3D

**Comment by atoulme** [comment]
Here is a video posted on Youtube: https://www.youtube.com/watch?v=qHJY5kK_Nbo

Thanks all for attending. I will be posting notes from the meeting ASAP.

**Comment by w1g0** [comment]
Transcription of the Call: https://hackmd.io/@w1g0/B1PAArNWY
