### ISSUE TITLE
Enable Github Discussion Feature

### ISSUE THREAD

**Issue by stevanlohja** [ethereumclassic/ECIPs#435]
I'm proposing to enable [Github Discussions](https://github.blog/2021-08-17-github-discussions-out-of-beta/) for this repository to host ECIP discussions. Discussions often happen via Github Issues, but now we have this neat discussion feature for more organized discourse including the other community engagements and metrics Github Discussions offer.

I've assigned this issue to the ECIP editors. If you think this is a good idea, then I can move forward with setting this feature up. Let me know what you think.

**Comment by q9f** [comment]
https://github.com/ethereumclassic/ECIPs/discussions/436

**Comment by DonaldMcIntyre** [comment]
- Does this mean IOHK will discuss their proposals like the Treasury (which they haven't done) in public and not in back door secret channels? 

- So, are they going to respond objection by objection live and transparently? 

- Or, are they going to continue to wait until they have a large overwhelming reformed proposal to obfuscate with complexity all the flawed features of the Treasury?  

- Or, is the Treasury an exception because you are negotiating bribes to different constituents to make it pass fraudulently?

**Comment by stevanlohja** [comment]
> * Does this mean IOHK will discuss their proposals like the Treasury (which they haven't done) in public and not in back secret channels?
> * So, are they going to respond objection by objection live and transparently?
> * Or, are they going to continue to wait until they have a large overwhelming reformed proposal to obfuscate with complexity all the flawed features of the Treasury?
> * Or, is the Treasury an exception because you are negotiating bribes to different constituents to make it pass fraudulently?

I would regress from your outlandish comment and keep the conversation relevant and professional to the issue at hand. This issue was a transparent inquiry to fellow repo maintainers to enable the repo _discussions_ feature which is now available on Github. This feature is purpose-built for discussions and has a mini forum-like structure available to everyone.

**Comment by gitr0n1n** [comment]
I see no downside to increasing community engagement in the github repo where ECIPs live and the control of the repo is sufficiently decentralized. This could help build resilience to corporate capture of ETC socials, as its another avenue to communicate openly. Although I haven't had experience using this feature, the logic behind the suggestion seems sound and beneficial to the ETC project to me.

**Comment by bobsummerwill** [comment]
Thanks for bringing this up, @stevanlohja.
Looks like it should be very useful.

**Comment by DonaldMcIntyre** [comment]
> > * Does this mean IOHK will discuss their proposals like the Treasury (which they haven't done) in public and not in back secret channels?
> > * So, are they going to respond objection by objection live and transparently?
> > * Or, are they going to continue to wait until they have a large overwhelming reformed proposal to obfuscate with complexity all the flawed features of the Treasury?
> > * Or, is the Treasury an exception because you are negotiating bribes to different constituents to make it pass fraudulently?
> 
> I would regress from your outlandish comment and keep the conversation relevant and professional to the issue at hand. This issue was a transparent inquiry to fellow repo maintainers to enable the repo _discussions_ feature which is now available on Github. This feature is purpose-built for discussions and has a mini forum-like structure available to everyone.

You may regress. 🤣
