### ISSUE TITLE
ETC Core Devs Call 20

### ISSUE THREAD

**Issue by stevanlohja** [ethereumclassic/ECIPs#449]
**Agenda**:

- Cleanup ECIP repo [Issues](https://github.com/ethereumclassic/ECIPs/issues)
- Follow-up on https://github.com/ethereumclassic/ECIPs/discussions/448
- Follow-up on https://github.com/ethereumclassic/ECIPs/discussions/440

**How to join**:

Topic: ETC Core Devs Call 20
Time: Nov 18, 2021 10:00 AM Central Time (US and Canada)

Join Zoom Meeting
https://us02web.zoom.us/j/84888164918?pwd=cmpUak9tZ1N5akZrUGlReWNWSjJydz09

Meeting ID: 848 8816 4918
Passcode: sudoetc

_Add this to your calendar so you don't miss it!_ 📅

**Comment by w1g0** [comment]
Time: 4 PM or 16h00 UTC

**Comment by q9f** [comment]
10am CST is not 4pm UTC

**Comment by w1g0** [comment]
In stead of stating what it is not, maybe you can say what it is?

**Comment by w1g0** [comment]
![2021-11-02_19h03_39](https://user-images.githubusercontent.com/67763069/139920791-13cd53a8-d837-4f50-b27a-1a1afdb3e060.png)

**Comment by bobsummerwill** [comment]
We should add Mystique discussion to the agenda too.

Also, would it be possible to have this call on the Thursday, rather than the Friday?
I have been unable to attend any of the last 2-3 calls, because of family commitments (school run) which I have ONLY on Fridays and only at that time.

**Comment by bobsummerwill** [comment]
@meowsbits @diega @ziogaschr @iquidus @atoulme

**Comment by w1g0** [comment]
It was said in meeting #18 and repeated in #19 that Friday wasn't the best timing, so I agree. Thursday 18th works for me!

**Comment by ziogaschr** [comment]
Thursday works for me as well.

**Comment by stevanlohja** [comment]
~~Nov 19~~  ➡️ Nov 18

**Comment by iquidus** [comment]
Thursday works for me also

**Comment by jpcomps** [comment]
Any plans to follow up on  ECIP-1107 from Dev Call 19? Perhaps can be added to the end of the meeting if time allows, or scheduled for 21.  @atoulme @meowsbits @bobsummerwill

**Comment by brolal** [comment]
![Screenshot from 2021-11-18 04-38-59](https://user-images.githubusercontent.com/82910708/142341708-ef0b6fb4-83f4-4faa-90cf-ced1c382a4e6.png)

**Comment by stevanlohja** [comment]
Thanks for attending the call everyone. Short summary:

- We cleaned-up outstanding ECIP issues and I'll ping the authors of any old ones before officially closing them.
- We discussed ECIP-Editor changes, thanks Antoine and Istora for volunteering to join as ECIP Editors.
- We discussed Mystique, this would be easy for Besu and Core-geth to merge and drop a release. No one expressed the upgrade to be contentious.
-  We discussed keccak and pow switching. Besu has this ready and Core-geth is WIP, but expressed interest in a controlled experiment.
- If you can, utilize the Discussion feature in the repo :) https://github.com/ethereumclassic/ECIPs/discussions
