### ISSUE TITLE
ETC Core Devs Call 21

### ISSUE THREAD

**Issue by diega** [ethereumclassic/ECIPs#457]
### Agenda:
  * Discuss upcoming Mystique EVM incompatibilities
  * Set new dates for https://github.com/ethereumclassic/ECIPs/discussions/440
  * Discuss https://github.com/ethereumclassic/ECIPs/discussions/456

### How to join:
Topic: ETC Core Devs Call 21
Time: Dec 21, 2021 12:00 PM Central Time (US and Canada) 🎄

Join Zoom Meeting
https://zoom.us/j/7100429487

Add this to your calendar so you don't miss it! 📅

**Comment by IstoraMandiri** [comment]
Was there a recording of this meeting?

**Comment by w1g0** [comment]
https://open.lbry.com/@Ethereum_Classic:2/2021-12-27_18h18_45:2?r=9fiA7tQP5nTkSV9Mm3bNcyAaPLp1Fe9Q

**Comment by stevanlohja** [comment]
This meeting is completed. Thank you @diega
