### ISSUE TITLE
Discussion: Rework the Uncle Rewards to Decentralize Miner Emission

### ISSUE THREAD

**Issue by gitr0n1n** [ethereumclassic/ECIPs#461]
This has been noted in the discord numerous times. We likely need to look at how our uncle rewards are currently processing and adjust this to help decentralize the mining emission. Please add to the discussion if you're informed on this. I'd like to get an ECIP in motion on this one when the miners have had a chance to give their input on what they think is the best incentive for network security for the long-term while we work our way through the 5M20 monetary policy.

it's my understanding these rewards dropped off in Era 3 or 4 of the 5M20 and feedback from miners is that it has a negative effect on the incentive system.

**Comment by stevanlohja** [comment]
Moved to ECIP _Discussions_ https://github.com/ethereumclassic/ECIPs/discussions/462
