### ISSUE TITLE
Unique token name on Ethereum Classic

### ISSUE THREAD

**Issue by w1g0** [ethereumclassic/ECIPs#498]
To prevent multiple projects to launch the same token name and ticker. This would reduce the chance on fraudulent projects and add extra security on verification with contract address.

**Comment by bobsummerwill** [comment]
What do you mean by "unique token name"?

A registry of ERC-20 tokens on top of ETC chain?

**Comment by stevanlohja** [comment]
This issue may be out-of-scope of an ECIP, but this might be the solution you're looking for: 
https://docs.blockscout.com/for-users/verifying-a-smart-contract

**Comment by w1g0** [comment]
I will close this issue until I can express myself clearer on this topic TBC
