### ISSUE TITLE
ECIP-1000: ECIP Process

### ISSUE THREAD

**Issue by sorpaas** [ethereumclassic/ECIPs#58]
[Rendered](https://github.com/ethereumclassic/ECIPs/blob/master/ECIPs/ECIP-1000.mediawiki)

An Ethereum Classic Improvement Proposal (ECIP) is a design document providing information to the Ethereum Classic community, or describing a new feature for Ethereum Classic or its processes or environment. The ECIP should provide a concise technical specification of the feature and a rationale for the feature.

We intend ECIPs to be the primary mechanisms for proposing new features, for collecting community input on an issue, and for documenting the design decisions that have gone into Ethereum Classic. The ECIP author is responsible for building consensus within the community and documenting dissenting opinions.

Because the ECIPs are maintained as text files in a versioned repository, their revision history is the historical record of the feature proposal.

**Comment by YazzyYaz** [comment]
@sorpaas I'm also thinking it might prove useful to adopt other improvement proposals and rebrand them as ECIPs with proper references to original authors and the original URLS.

For example, if we adopt an EIP, we can just label it as an ECIP-E. If we adopt an ECLIP, we can just label it as an ECIP-L. Naturally, then ECIPs are original community written proposals and the lettering applies to external improvement proposals.

**Comment by TheEnthusiasticAs** [comment]
So, now I am in here too. The general idea from @YazzyYaz is good. A one thing to this: The chosen acronym should be clear, to exclude the double interpretation.

**Comment by kimisan** [comment]
I will contribute some d3.js viz code based on it , wait me ^^

**Comment by phyro** [comment]
Thanks for starting the discussion sorpaas. I'm not familiar with the assigning a number part. Do we mean that when a PR is ready we tell the author to change the filename of the ECIP and the auxiliary files to include the number and then merge?

> Software authors are encouraged to publish summaries of what ECIPs their software supports to aid in verification of status changes

The links for these examples are dead (so are some other things like the process image but this can be fixed later). What I wanted to mention here is that if openrpc becomes a thing perhaps we should encourage the node clients to add the the ECIPs implemented as some sort of metadata (if anyone is interested in what i'm talking about here is the ECLIP https://github.com/etclabscore/ECLIPs/pull/3)

**Comment by sorpaas** [comment]
@phyro 

> Do we mean that when a PR is ready we tell the author to change the filename of the ECIP and the auxiliary files to include the number and then merge?

Yes. If we follow the process strictly, the author will first name the spec `ECIP-description-of-functionality.md`. The editors will then assign a number to the ECIP, and change the filename.

In practice it's mostly alright if we just let the author of the ECIP to assign the number by him/herself -- EIP uses the number same as the Github PR number, and for ECIP we previously use the next available one. I will update this ECIP to reflect this.

**Comment by zoulaihui** [comment]
Thank you Wei for creating this issue. I don't understand why there is ECLIP? What is the necessary to create a new protocol improvement standard for ETC?

**Comment by TokenHash** [comment]
I agree to move this ECIP to `Final Call`.

I also agree to add  @sorpaas, @isaac, @DontPanicBurns, and @soc1c as editors.

I recommend to add:

@phyro @kimisan @YazzyYaz @BelfordZ @shanejonas

**Comment by sorpaas** [comment]
@TokenHash I think we'd better look for developers to be on the editors list. I agree @phyro and @kimisan have contributed a lot, but they may not be able to help a lot in the case of technically reviewing ECIPs.

My only objections for adding @BelfordZ and @shanejonas is that we may then have too many representatives from ETCLabs (we already have two -- @isaac and @soc1c). But that's just my opinion and it's up to everyone.

**Comment by TokenHash** [comment]
Agreed, if they are not devs, but I thought they were.

**Comment by TokenHash** [comment]
Agreed, with balancing the devs from ETC Labs to other teams.

Maybe @elaineo and @mikeyb want to join.

**Comment by phyro** [comment]
Both me and Kimi are devs, but to actually give a meaningful comment, you need to have the background of how Ethereum protocol exactly works. I don't really have the background needed to give a reasonable comment for many of the ECIPs. I'll still comment on the ECIPs that I do understand so that's fine from my side :+1:

**Comment by sorpaas** [comment]
(If they're okay with editor responsibilities and self-identify as devs.)

**Comment by stevanlohja** [comment]
The ECIP editor simply needs to make sure the ECIP is properly formatted and curate the ECIP through the process with the author. Even if the Editor feels the context is technically unsound or likely to be rejected, they're commited is to curate the ECIP not be technical gateways. E.g.: Existing cold-staking and treasury ECIPs in the repo here.

**Comment by YazzyYaz** [comment]
Taking the comment here from discord; RE: I'd like to be added as editor.

**Comment by sorpaas** [comment]
FYI, I merged the draft initial list https://github.com/ethereumclassic/ECIPs/pull/94. If you want to add yourself or add others as editors, please just open a new PR against master branch!

**Comment by bobsummerwill** [comment]
Can we close this issue now, @sorpaas?  It was merged.
