### ISSUE TITLE
ECIP-1059: Address-to-Address message system

### ISSUE THREAD

**Issue by Dexaran** [ethereumclassic/ECIPs#63]
< Placeholder >

**Comment by soc1c** [comment]
Hi, 1055 is flyclient, what about 1059?

ref https://github.com/etclabscore/ECIPs/pull/11

ref https://github.com/ethereumclassic/ECIPs/pull/61

**Comment by bobsummerwill** [comment]
There is no actual proposal here.  Please can we close this?
