### ISSUE TITLE
ECIP-1057: Cold Staking

### ISSUE THREAD

**Issue by Dexaran** [ethereumclassic/ECIPs#65]
### Title

```
    ECIP: 1057
    Title: Cold Staking
    Author: Dexaran, dexaran@ethereumclassic.org
    Discussions-To: dexaran@ethereumclassic.org
    Status: Draft
    Type: Standard Track - Consensus
    Created: 2019-3-31
```

### Abstract

The following describes the implementation of the protocol, which is designed to reward ETC holders for the long term holding of their coins, thereby creating a scarcity and reducing the actual “circulating supply”. We already have a working prototype and a live version in Callisto Network as well as we have UI and all the necessary descriptions and guidelines.

This proposal is fully compatible with ECIP-1017 since it does not affect the actual monetary policy, but only the distribution of emitted coins. 

### Motivation

**Cold Staking is not a consensus protocol!**

#### 1. Rebalance the influence of miners and stakeholders

There are many participants in crypto networks: miners, investors and stakeholders, developers and media resource owners. Miners control the network hashrate, developers and media resource owners participate in hardforks directly, while stakeholders often have not so much power. In addition, the wealth, the hashrate share and the influence of miners increase with time as they receive payments so that they can acquire new mining equipment in order to have more hashpower. In ETC, the share of long term stakeholders do not increase with time.

From a fundamental point of view, it is better if the situation is opposite because:

1. The miners are not interested in the project they are mining. In general, miners are only interested in their income. They can switch at any time regardless of anything, so they have no long-term interest in the network to which they contribute. In most cases, miners have absolutely no incentives to hold assets they are mining. **The more power miners have, the greater the dumping potential of the mineable crypto asset.**

2. Long term investors and stake holders are interested in project they invest in. In most cases, large investors conduct significant research before making their long-term investments. The more they invest, the more tied to the project they are because they can't just "switch" at any point of time like miners. **The more power long-term investors have, the greater the upside potential of the asset.**

3. Long term investors are interested in the ecosystem and they have incentives to contribute their resources for the sake of long-term results.

I believe that it is important to implement a protocol that will balance the distribution of influence between miners and stakeholders in order to form a healthy ecosystem for the Ethereum Classic project.

#### 2. Financial incentives

Cold Staking can push the price of a crypto asset higher and increase its upside potential.

The Cold Staking protocol is based on the "gym market theory". You can find a description [here](https://docs.google.com/document/d/1LpRHzW7gGV1JfiXUQOmW-UEVF9TCNNWrYiItDuLgiGA/edit). Cold Staking reduces the actual circulating supply by incentivizing long-term stakeholders to lock their funds in a special contract. The more funds are blocked, the scarcer the crypto asset is, the higher the price can become during the bullish phase of the market. The higher the price of a crypto asset is, the greater the incentives for long-term investors (cold stakers) and so on.

### Specification

The proposal is to implement a protocol that will reward long-term holders for holding their coins:

- Allocate `<X>` % of mined block reward for Cold Stakers (cold staking fee).

- Allow any stakeholder to become a Cold Staker by locking his (her) funds in a special smart-contract for 27 days.

- Distribute a total sum of cold staking fees between cold stakers in proportion to their locked stake.

It is proposed to set the Cold Staking fee to 40% at the moment of the implementation and increase the Cold Staking fee share by 5% at block 15,000,000 and block 20,000,000 (these are blocks of mining reward reduction according to ECIP1017).

| Block interval | Block Reward | Mining, % | Cold Staking, % | Monthly return (assuming that 1/2 of total ETC supply is locked in staking) |
| ---: | ---: | ---: | ---: | ---: |
| 1 - 10,000,000 | 5 ETC | 100% | 0% | - |
| 10,000,000 - 15,000,000 | 4 ETC | 60% | 40% | 0.36% |
| 15,000,000 - 20,000,000 | 3.2 ETC | 55% | 45% | 0.28% |
| 20,000,000 - 25,000,000 | 2.56 ETC | 50% | 50% | 0.23% |
| 25,000,000 - ... | 2.05 ETC | 50% | 50% | 0.17% |

More detailed calculations are described in [this google spreadsheet](https://docs.google.com/spreadsheets/d/1aKCvHoodbyNU-TGcJIwcvucXHJI_HwwOcbNtJGB8ES8/edit?usp=sharing).

The described system is self-balancing, which means that with the decrease of the staking reward the stakers will pull out, decreasin the total "Cold Staking pool", thus increasing the share of the rest of the stakers, therefore their reward will increase until it will settle at the level where the system is balanced.

However, we should consider the viability of the system assuming that 50% of the total circulating supply will go into Cold Staking. This numbers are empirically proven to be essential.

Most of the stakeable crypto assets such as [Dash](https://stakingrewards.com/asset/dash) or [PIVX](https://stakingrewards.com/asset/pivx) have 4 to 8 % of annual return rate. DASH or PIVX masternode requires a hardware that will participate in the generation of blocks, while Cold Staking do not require cold stakers to perform any actions apart from pressing "start staking" and "claim reward" buttons. The minimal Cold Staking return at 50% of total supply at stake should be comparable to the return of DASH or PIVX masternodes. With that being said I can conclude that 4% of the annual yield from Cold Staking is affordable for the viability of the system at the launch stage.

#### Staking round length should be equal to 27 days

Traders often make their decisions based on charts and candle closures. Therefore, it is better for them to have their coins available when the time to make a decision will come. That's why I'm proposing 27 days interval. 

If you deposit your funds at the beginning of a month then you will have the opportunity to claim it back right before the closure of the (1) week candle and (2) month candle at the same time.

![candle_close](https://user-images.githubusercontent.com/26142412/46502950-7ae0a080-c83a-11e8-8d21-60f9e9a95391.png)

### References

- [Staking Formula](https://docs.google.com/document/d/1uckDVbgAj6N6Nx6Sm8-CnL_kRJTT8MZRQfVEkT01ltM/edit)

- [Everything you need to know about Callisto Cold Staking](https://www.reddit.com/r/CallistoCrypto/comments/9qe5bm/everything_you_need_to_know_about_cold_staking/)

- [Cold Staking contract development discussion](https://github.com/EthereumCommonwealth/Roadmap/issues/51)

- [What is Cold Staking? (Callisto)](https://callisto.network/cold-staking/)

- [Step-By-Step tutorial: Staking with ClassicEtherWallet](https://callisto.network/ru/blog/post/cold-staking-a-step-by-step-tutorial/)

- [Cold Staking at Testnet](https://callisto.network/blog/post/callisto-cold-staking-testnet-implementation)

### Implementation

This protocol consists of two parts: (1) protocol-level implementation and (2) smart-contract.

1. Protocol-level implementation requires a hardfork. Starting from the hardfork block number, a certain amount of ETC should be allocated for the Cold Staking contract address with each mined block. Protocol-level implementation is only required to enable the Cold Staking.

2. The smart-contract implements the logic of the Cold Staking protocol. The source code of the Cold Staking contract can be found [here](https://github.com/EthereumCommonwealth/Cold-staking). Cold Staking contract was [audited](https://github.com/EthereumCommonwealth/Auditing/issues/77). [Bug bounty](https://github.com/EthereumCommonwealth/Roadmap/issues/52) was held. The contract has a working implementation at Callisto Network.

#### Live implementation at Callisto Network

This is the live Cold Staking contract at Callisto Network: [0xd813419749b3c2cDc94A2F9Cfcf154113264a9d6](https://explorer2.callisto.network/addr/0xd813419749b3c2cDc94A2F9Cfcf154113264a9d6)

Cold Staking UI is already implemented in [ClassicEtherWallet](http://classicetherwallet.com) (only visible when unlocking wallet with CLO network nodes selected).

Cold Staking is supported by [Guarda wallet](https://www.reddit.com/r/CallistoCrypto/comments/9z2tmt/callisto_cold_staking_is_now_active_on_guarda/), [Trust wallet](https://trustwallet.com/assets/callisto) and some other wallets.

**Comment by shanejonas** [comment]
I emoji’d thumbsdown, my initial thoughts are that the PoW is what secures the network and should be rewarded as such.

But I can understand how other networks might use a scheme like this to attract a certain type of investor.

**Comment by pyskell** [comment]
Agree with Shane. Weakens security and changes a monetary policy that is permanent. May not change emission, certainly changes the policy in material ways by changing where block rewards go.

PoW is predicated on incentivizing miners to secure the network. Full stop.

**Comment by phyro** [comment]
Personally, I believe the reward should fully go to miners. I *might* support some change in how the reward is distributed between them if it made sense, but as Shane and pyskell mentioned, if you reduce the miners reward, you reduce the security.

**Comment by kimisan** [comment]
Thanks for the proposal.
But I think this kind of Cold Staking would make our system more complicate.

**Comment by feqifei** [comment]
I voted thumbup because I hope dexaran's proposal could be discussed without prejudice.
I'm following recent discussions on Discord about the possibility ETC will become a security layer for ETH and other cryptos. I understand that the risk of a reward system for holders can can reduce the security as consequence of a decreased reward for miners.
On the other hand if ETC will be a L1 of other PoS cryptos it will become a kind of commodity and I don't see the advantage for holders.

Disclaimer: I'm a long-term holder

**Comment by frankbuse** [comment]
Thumbs up from me.
This should be implemented asap. 

I don't understand the comment “if you reduce the miners reward, you reduce the security“

Old etc  keepers/miners and new miners/buyers will get an extra reason to keep their mining rewards or their bought etc because they can now stake their etc and get rewarded for holding.

So this would attract new miners, get some buying volume because staking is getting more and more accepted. 
And also as the total staking balance grows, the ones staking would all benefit from a higher ETC price so their 27 days rewards will go up dollar wise

**Comment by phyro** [comment]
@feqifei I think everyones opinion so far was based on reasoning. ETC should not care whether people use it as L1, anyone is free to do it.
@frankbuse you're assuming miners care about ETC which is false - also this ECIP mentions that `The miners are not interested in the project they are mining`

What ECIP tries to accomplish is to prevent people from withdrawing their money to prevent possible huge dumps of ETC. My guess is that smart investors won't lock themselves in anyway.

**Comment by soc1c** [comment]
I would like to remind everyone that accepting a proposal as _draft_ does not imply any governance and that GitHub is not the best place to debate whether a proposal should be accepted or not.

The ECIP process accepts any _technical sound_ proposal as a draft as long as it meets basic technical standards and follows the process strictly. The actual governance and acceptance or rejecting process start _after_ the technical discussion on Github.

**Comment by anotherVariable** [comment]
If all you have to do is lock up some ETC to get some back, what incentive does that give to the miners to keep on mining who keep the network secure?

Especially when cold staking wants to take away from the miner reward, and split it up to someone that just does nothing, but puts some ETC in a smart contract and walks away for 27 days.

The chain doesn't need any more so called `hodlers` it needs people that use it every day not once every 27 days. 😉 

Also from what I remember the CLO network hash feel by quite a bit, right after cold staking was introduced? I know I quit mining and just started staking. 😄

**Comment by drd34d** [comment]
> Motivation:
> 1. Rebalance the influence of miners and stakeholders
> The more power miners have, the greater the dumping potential of the mineable crypto asset.
> The more power long-term investors have, the greater the upside potential of the asset.
> 
> 2. Financial incentives
> Cold Staking can push the price of a crypto asset higher and increase its upside potential.

A proposal which the motivation is admitedly financial benefits for stakeholders, at the cost of reduction of mining rewards (and it's predictable consequences, ie: reduction of networh hash), it's surely not an "improvement" imo.

Imo "dumping potential" and price shouldn't be something devs should be worrying about at the moment.

Also, in case you didn't know, "investors" and stakeholders will "dump" as soon as the price hits their targets, as long as the profit is bigger than the stake rewards.

**Comment by YazzyYaz** [comment]
I am following @soc1c lead in saying any technically-sound draft ECIP proposals that follow the format should be accepted, and debates and discussions about them that are non-technical but more political and financial should happen out of Github. Discord ECIP channels are a great place for debate, as well as Twitter.

**Comment by tzdybal** [comment]
I don't agree with @YazzyYaz and @soc1c. All those comments are on the "issue", not "pull request" started by @Dexaran - I would guess that this is the place of his choice for discussion.
IMHO PR should be accepted, because ECIP is "sound" and OK from editorial point of view. And discussion can be continued in here. 
Discussion in Discord are IMHO not good, because there are many ECIPs, and off-topics discussed in there and searching/archiving/recalling such discussion is rather hard. 

And now, to the point...
I don't agree with this proposal. As mentioned before, taking money from miners and giving it to the hodlers probably would reduce hash rate (as miners will be deincentivized)
I would also say that this *is* about monetary policy.
Addressing the "fundamental" part:
1. With decreased block reward, miners will be even less interested in mining ETC at all.
2. IMHO, most "long time investors" can at most shill the coin on Twitter. They can't switch easily, only if they invested out-of-chain, for example funded dev team or incubator. And in such case, they won't gain from staking. OFC they can also stake, but the part of investment that makes it harder to switch is not giving cold stake incentives. 
3. What kind of "valuable" investors can be attracted? Individual developers that do cold staking + develop in the ecosystem? Big companies that can afford staking and funding of dev teams, dApps, tools, etc? IMHO they would/wouldn't invest in ETC anyways, because of general characteristics of the chain. Startups? They probably won't have money for staking.

I'm against adopting this ECIP, because:
* it changes the rules of the game for miners / changes monetary policy
* its main goal is to change ETC price / valuation
* influence of stakeholders won't be "rebalanced" - they will only get some reward for cold staking, but it won't change the way they "influence" the network - they can participate in community right now, and after this change they won't get any extra power / rights
* in my opinion it doesn't improve anything except profits of some network participants

**Comment by stevanlohja** [comment]
Holdings in exchange for dividends put staking participants at risk to securities laws as well as the perception of our network. SEC says Ethereum is not a security - let's keep in that way.
