### ISSUE TITLE
ECIP-1054: Atlantis EVM and Protocol Upgrades

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/ECIPs#67]
Atlantis Hardfork Meta
Enable the outstanding Ethereum Foundation Spurious Dragon and Byzantium network protocol upgrades on the Ethereum Classic network in a hard-fork code-named Atlantis to enable maximum compatibility across these networks.

![etcatlantis_copy](https://user-images.githubusercontent.com/47772477/54919046-11477200-4f00-11e9-84f5-f767085e355b.jpg)

To Discussion to : https://github.com/etclabscore/ECIPs/pull/10

**Comment by soc1c** [comment]
What's the point of this ticket?

**Comment by YazzyYaz** [comment]
@soc1c to add a `Discussions-To` to the preamble.

**Comment by meowsbits** [comment]
Where should the discussions go to?

**Comment by soc1c** [comment]
here or here: https://github.com/ethereumclassic/ECIPs/issues/78
