### ISSUE TITLE
ECIP-1000 license needs verification

### ISSUE THREAD

**Issue by realcodywburns** [ethereumclassic/ECIPs#98]
BIP 001 the following text can be found:

```
This document was derived heavily from Python's PEP-0001. In many places text was simply copied and modified. Although the PEP-0001 text was written by Barry Warsaw, Jeremy Hylton, and David Goodger, they are not responsible for its use in the Bitcoin Improvement Process, and should not be bothered with technical questions specific to Bitcoin or the BIP process. Please direct all comments to the BIP editors or the Bitcoin development mailing list.
``` 
the ECIP-1000 points to luke-jr as the copy right holder. If he is, we need to properly link to the license, if not it needs to be addressed with the proper license

**Comment by TokenHash** [comment]
I think the correct comparable BIP is BIP-0002:

https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki

That was written for Bitcoin by @luke-jr, but it is based on something else. I think it was based on:

https://tools.ietf.org/html/rfc7282

**Comment by bobsummerwill** [comment]
I don't see any issue here, @realcodywburns.

As per https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki, that is 

https://spdx.org/licenses/BSD-2-Clause.html

Which is a weaker permissive license than the Apache 2 which @sorpaas uses for ECIP-1000.

What do you think we are missing here?   Perhaps just a link to https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki from ECIP-1000?
